import { AnimationStep, BSTNode } from '../types';

export function getAnimationStepsForLesson(lessonId: string, lessonNumber: number): AnimationStep[] {
  switch (lessonNumber) {
    case 1: // What is a Tree
      return [
        {
          stepNumber: 1,
          totalSteps: 4,
          treeValues: [40, 20, 60],
          activeNodeId: 'node-40',
          nodeLabels: { 'node-40': 'ROOT NODE' },
          comparisonBanner: { text: 'Entry Point: Root Node (40)', subtext: 'Topmost node with no parents above it', direction: 'INFO' },
          title: 'Step 1: Identify the Root',
          explanation: 'Every tree starts with a single top boss node called the Root. Here, node 40 is the Root.',
        },
        {
          stepNumber: 2,
          totalSteps: 4,
          treeValues: [40, 20, 60],
          highlightedNodeIds: ['node-20', 'node-60'],
          nodeLabels: { 'node-40': 'PARENT', 'node-20': 'LEFT CHILD', 'node-60': 'RIGHT CHILD' },
          comparisonBanner: { text: 'Branches to Child Nodes', subtext: '40 connects downward to 20 and 60', direction: 'INFO' },
          title: 'Step 2: Follow the Branches (Edges)',
          explanation: 'From the root 40, lines (edges) branch out downwards to two child nodes: 20 on the left and 60 on the right.',
        },
        {
          stepNumber: 3,
          totalSteps: 4,
          treeValues: [40, 20, 60],
          correctNodeIds: ['node-20', 'node-60'],
          nodeLabels: { 'node-40': 'ROOT', 'node-20': 'LEAF', 'node-60': 'LEAF' },
          comparisonBanner: { text: 'Bottom Nodes = Leaves', subtext: 'Nodes with 0 children at the bottom', direction: 'INFO' },
          title: 'Step 3: Reach the Leaves',
          explanation: 'Nodes 20 and 60 have no further children branching from them. Nodes at the bottom are called Leaf nodes.',
        },
        {
          stepNumber: 4,
          totalSteps: 4,
          treeValues: [40, 20, 60],
          correctNodeIds: ['node-40', 'node-20', 'node-60'],
          comparisonBanner: { text: 'Hierarchical Structure Complete', subtext: 'No cycles, clear top-down levels', direction: 'INFO' },
          title: 'Step 4: Tree Properties Satisfied',
          explanation: 'The structure forms an inverted tree: 1 Root at the top, branching downward to Leaves without any loops or cycles.',
        },
      ];

    case 2: // Binary Tree
      return [
        {
          stepNumber: 1,
          totalSteps: 3,
          treeValues: [50],
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'ROOT' },
          comparisonBanner: { text: 'Node 50 (0 Children)', subtext: 'Binary tree allows 0, 1, or 2 children', direction: 'INFO' },
          title: 'Step 1: Check Node 50',
          explanation: 'In a Binary Tree, each node can have at most TWO children (Left and Right). Currently node 50 has 0 children (valid).',
        },
        {
          stepNumber: 2,
          totalSteps: 3,
          treeValues: [50, 30],
          highlightedNodeIds: ['node-30'],
          nodeLabels: { 'node-50': 'PARENT', 'node-30': 'LEFT CHILD' },
          comparisonBanner: { text: 'Node 50 gains Left Child (30)', subtext: 'Children count: 1 (valid <= 2)', direction: 'LEFT' },
          title: 'Step 2: Add Left Child 30',
          explanation: 'We attach 30 to the left branch. Node 50 now has 1 child. This is valid.',
        },
        {
          stepNumber: 3,
          totalSteps: 3,
          treeValues: [50, 30, 70],
          correctNodeIds: ['node-50', 'node-30', 'node-70'],
          nodeLabels: { 'node-50': 'PARENT', 'node-30': 'LEFT', 'node-70': 'RIGHT' },
          comparisonBanner: { text: 'Node 50 has 2 Children: Left & Right', subtext: 'Maximum capacity reached for node 50', direction: 'INFO' },
          title: 'Step 3: Add Right Child 70',
          explanation: 'We attach 70 to the right branch. Node 50 has 2 children (Full). No node can have a 3rd child in a binary tree.',
        },
      ];

    case 3: // What is a BST
    case 4: // BST Property (The Golden Rule)
      return [
        {
          stepNumber: 1,
          totalSteps: 4,
          treeValues: [50],
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'ROOT (50)' },
          comparisonBanner: { text: 'Root Node = 50', subtext: 'All Left < 50 | All Right > 50', direction: 'INFO' },
          title: 'Step 1: Inspect the Root Value',
          explanation: 'In a Binary Search Tree (BST), the root 50 acts as the reference point for all other values.',
        },
        {
          stepNumber: 2,
          totalSteps: 4,
          treeValues: [50, 30],
          activeNodeId: 'node-30',
          nodeLabels: { 'node-50': 'ROOT (50)', 'node-30': '30 < 50 (LEFT)' },
          comparisonBanner: { text: '30 < 50 → Belongs on LEFT', subtext: 'Left subtree elements must be strictly smaller', direction: 'LEFT' },
          title: 'Step 2: Left Child Rule (Smaller)',
          explanation: 'Because 30 is less than 50 (30 < 50), it MUST be placed in the Left Subtree.',
        },
        {
          stepNumber: 3,
          totalSteps: 4,
          treeValues: [50, 30, 70],
          activeNodeId: 'node-70',
          nodeLabels: { 'node-50': 'ROOT (50)', 'node-30': 'LEFT', 'node-70': '70 > 50 (RIGHT)' },
          comparisonBanner: { text: '70 > 50 → Belongs on RIGHT', subtext: 'Right subtree elements must be strictly greater', direction: 'RIGHT' },
          title: 'Step 3: Right Child Rule (Greater)',
          explanation: 'Because 70 is greater than 50 (70 > 50), it MUST be placed in the Right Subtree.',
        },
        {
          stepNumber: 4,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          correctNodeIds: ['node-50', 'node-30', 'node-70', 'node-20', 'node-40', 'node-60', 'node-80'],
          comparisonBanner: { text: '★ BST Property: Left < Root < Right', subtext: 'Holds recursively for every single subtree in the tree', direction: 'INFO' },
          title: 'Step 4: Golden Rule for the Whole Tree',
          explanation: 'For EVERY node: Left is always smaller, Right is always greater. This allows O(log n) fast search!',
        },
      ];

    case 8: // Insertion Walkthrough
      return [
        {
          stepNumber: 1,
          totalSteps: 5,
          treeValues: [40, 20, 60],
          comparingValue: 25,
          activeNodeId: 'node-40',
          nodeLabels: { 'node-40': 'COMPARE (40)' },
          comparisonBanner: { text: 'Insert 25: Compare 25 with 40', subtext: '25 < 40 → Move to LEFT child', direction: 'LEFT' },
          title: 'Step 1: Compare with Root (40)',
          explanation: 'We want to insert 25. We begin at root 40. Since 25 < 40, we move down to the Left child.',
        },
        {
          stepNumber: 2,
          totalSteps: 5,
          treeValues: [40, 20, 60],
          comparingValue: 25,
          activeNodeId: 'node-20',
          nodeLabels: { 'node-40': 'ROOT', 'node-20': 'COMPARE (20)' },
          comparisonBanner: { text: 'Compare 25 with 20', subtext: '25 > 20 → Move to RIGHT child of 20', direction: 'RIGHT' },
          title: 'Step 2: Compare with Left Child (20)',
          explanation: 'At node 20, compare: 25 > 20. Since 25 is greater, we look for the Right child of 20.',
        },
        {
          stepNumber: 3,
          totalSteps: 5,
          treeValues: [40, 20, 60],
          comparingValue: 25,
          nodeLabels: { 'node-40': 'ROOT', 'node-20': 'PARENT' },
          comparisonBanner: { text: 'Right of 20 is EMPTY', subtext: 'Found the correct insertion spot!', direction: 'INSERT' },
          title: 'Step 3: Found Empty Insertion Spot',
          explanation: 'Node 20 currently has no right child. This empty slot is the exact spot where 25 belongs.',
        },
        {
          stepNumber: 4,
          totalSteps: 5,
          treeValues: [40, 20, 60, 25],
          correctNodeIds: ['node-25'],
          nodeLabels: { 'node-40': 'ROOT', 'node-20': 'PARENT', 'node-25': 'NEW NODE (25)' },
          comparisonBanner: { text: '✓ 25 Successfully Inserted!', subtext: '20 < 25 < 40 (All BST rules preserved)', direction: 'INSERT' },
          title: 'Step 4: Place Node 25 and Link to Parent',
          explanation: 'Create a new node with value 25 and link it as the right child of 20.',
        },
        {
          stepNumber: 5,
          totalSteps: 5,
          treeValues: [40, 20, 60, 25],
          correctNodeIds: ['node-40', 'node-20', 'node-60', 'node-25'],
          comparisonBanner: { text: 'Tree is Valid BST!', subtext: 'Insertion complete in O(h) comparisons', direction: 'INFO' },
          title: 'Step 5: Verify BST Property',
          explanation: '25 is smaller than 40 (in left subtree) and larger than 20 (on right of 20). Insertion complete!',
        },
      ];

    case 9: // Search Walkthrough
      return [
        {
          stepNumber: 1,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          comparingValue: 60,
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'COMPARE (50)' },
          comparisonBanner: { text: 'Search 60: Compare 60 with Root 50', subtext: '60 > 50 → Go RIGHT', direction: 'RIGHT' },
          title: 'Step 1: Start at Root 50',
          explanation: 'Target is 60. Compare target with root: 60 > 50. We immediately discard the entire left subtree and move RIGHT.',
        },
        {
          stepNumber: 2,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          comparingValue: 60,
          activeNodeId: 'node-70',
          nodeLabels: { 'node-50': 'VISITED', 'node-70': 'COMPARE (70)' },
          comparisonBanner: { text: 'Compare 60 with 70', subtext: '60 < 70 → Go LEFT', direction: 'LEFT' },
          title: 'Step 2: Compare with 70',
          explanation: 'At node 70, compare target: 60 < 70. Since 60 is smaller, we move to the LEFT child of 70.',
        },
        {
          stepNumber: 3,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          comparingValue: 60,
          correctNodeIds: ['node-60'],
          nodeLabels: { 'node-70': 'PARENT', 'node-60': 'TARGET FOUND!' },
          comparisonBanner: { text: '🎯 60 == 60: TARGET FOUND!', subtext: 'Located in only 3 comparisons (O(log n))', direction: 'FOUND' },
          title: 'Step 3: Target Match at Node 60',
          explanation: 'At node 60: target 60 equals current node 60. Search is successful! Total comparisons: 3.',
        },
        {
          stepNumber: 4,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          correctNodeIds: ['node-50', 'node-70', 'node-60'],
          comparisonBanner: { text: 'Search Path: [50 → 70 → 60]', subtext: 'Half the remaining tree was skipped at each step', direction: 'FOUND' },
          title: 'Step 4: Search Path Summary',
          explanation: 'In a 7-node tree, we found our item in just 3 steps instead of checking all 7 nodes linearly.',
        },
      ];

    case 10: // Deletion Case 1: Leaf Node
      return [
        {
          stepNumber: 1,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40],
          activeNodeId: 'node-20',
          nodeLabels: { 'node-30': 'PARENT', 'node-20': 'TARGET (20)' },
          comparisonBanner: { text: 'Delete 20: Locate target node', subtext: '20 is on left side of parent 30', direction: 'DELETE' },
          title: 'Step 1: Locate Target Node 20',
          explanation: 'We want to delete node 20. Traverse the tree to find 20 under parent 30.',
        },
        {
          stepNumber: 2,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40],
          activeNodeId: 'node-20',
          nodeLabels: { 'node-20': '0 CHILDREN (LEAF)' },
          comparisonBanner: { text: 'Check Children Count: 0 Children', subtext: 'This is Case 1: Leaf Node Deletion', direction: 'INFO' },
          title: 'Step 2: Classify Deletion Case',
          explanation: 'Look at node 20: it has no left child and no right child. It is a Leaf Node (0 children).',
        },
        {
          stepNumber: 3,
          totalSteps: 4,
          treeValues: [50, 30, 70, 20, 40],
          invalidNodeIds: ['node-20'],
          nodeLabels: { 'node-30': 'PARENT', 'node-20': 'DISCONNECT' },
          comparisonBanner: { text: 'Sever Connection: Set 30.left = null', subtext: 'Simply remove the pointer from parent', direction: 'DELETE' },
          title: 'Step 3: Disconnect from Parent',
          explanation: 'Because a leaf has no children, we can delete it directly by setting parent 30\'s left pointer to null.',
        },
        {
          stepNumber: 4,
          totalSteps: 4,
          treeValues: [50, 30, 70, 40],
          correctNodeIds: ['node-50', 'node-30', 'node-70', 'node-40'],
          comparisonBanner: { text: '✓ Leaf 20 Deleted Cleanly', subtext: 'Remaining tree is intact and valid BST', direction: 'INFO' },
          title: 'Step 4: Final Tree State',
          explanation: 'Node 20 is completely removed. No other nodes had to be repositioned. Easy and clean!',
        },
      ];

    case 11: // Deletion Case 2: One Child
      return [
        {
          stepNumber: 1,
          totalSteps: 5,
          treeValues: [50, 30, 70, 60],
          activeNodeId: 'node-70',
          nodeLabels: { 'node-50': 'PARENT', 'node-70': 'DELETE (70)', 'node-60': 'ONLY CHILD (60)' },
          comparisonBanner: { text: 'Delete 70: Locate target node', subtext: '70 has exactly ONE child (60)', direction: 'DELETE' },
          title: 'Step 1: Locate Target Node 70',
          explanation: 'We want to delete 70. Node 70 is the right child of 50, and has only one child: 60.',
        },
        {
          stepNumber: 2,
          totalSteps: 5,
          treeValues: [50, 30, 70, 60],
          activeNodeId: 'node-70',
          highlightedNodeIds: ['node-60'],
          nodeLabels: { 'node-70': '1 CHILD', 'node-60': 'REPLACEMENT' },
          comparisonBanner: { text: 'Case 2: Node has 1 Child', subtext: 'Rule: Bypass node and connect parent directly to child', direction: 'INFO' },
          title: 'Step 2: Understand the 1-Child Rule',
          explanation: 'When a deleted node has only 1 child, that child simply steps up to take its parent\'s place.',
        },
        {
          stepNumber: 3,
          totalSteps: 5,
          treeValues: [50, 30, 70, 60],
          invalidNodeIds: ['node-70'],
          correctNodeIds: ['node-60'],
          nodeLabels: { 'node-50': 'PARENT', 'node-70': 'BYPASS', 'node-60': 'PROMOTE' },
          comparisonBanner: { text: 'Bypass 70 → Link 50.right to 60', subtext: 'Parent adopts grandchild directly', direction: 'REPLACE' },
          title: 'Step 3: Re-link Parent to Grandchild',
          explanation: 'We point root 50\'s right pointer directly to node 60, bypassing 70.',
        },
        {
          stepNumber: 4,
          totalSteps: 5,
          treeValues: [50, 30, 60],
          correctNodeIds: ['node-60'],
          nodeLabels: { 'node-50': 'ROOT', 'node-60': 'PROMOTED (60)' },
          comparisonBanner: { text: 'Node 70 Removed, 60 in Place', subtext: '60 > 50 so BST rule is completely satisfied', direction: 'INFO' },
          title: 'Step 4: Remove Node 70',
          explanation: 'Node 70 is discarded. Node 60 now sits directly under 50.',
        },
        {
          stepNumber: 5,
          totalSteps: 5,
          treeValues: [50, 30, 60],
          correctNodeIds: ['node-50', 'node-30', 'node-60'],
          comparisonBanner: { text: '✓ 1-Child Deletion Complete!', subtext: 'BST properties remain 100% valid', direction: 'INFO' },
          title: 'Step 5: Final Tree Validation',
          explanation: 'Left is 30 (< 50), Right is 60 (> 50). Perfect valid BST.',
        },
      ];

    case 12: // Deletion Case 3: Two Children (In-Order Successor)
    case 13: // In-Order Successor
      return [
        {
          stepNumber: 1,
          totalSteps: 6,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'DELETE ROOT (50)' },
          comparisonBanner: { text: 'Delete 50: Node has TWO Children!', subtext: 'Left (30) and Right (70) both exist', direction: 'DELETE' },
          title: 'Step 1: Detect Two Children Case',
          explanation: 'We want to delete 50. It has 2 children (30 and 70). We CANNOT simply delete 50, or the tree would split into two disconnected pieces!',
        },
        {
          stepNumber: 2,
          totalSteps: 6,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          activeNodeId: 'node-50',
          highlightedNodeIds: ['node-70'],
          nodeLabels: { 'node-50': 'TARGET', 'node-70': 'RIGHT SUBTREE' },
          comparisonBanner: { text: 'Find Replacement: In-Order Successor', subtext: 'Rule: Go RIGHT once, then all the way LEFT', direction: 'RIGHT' },
          title: 'Step 2: Search for In-Order Successor',
          explanation: 'The In-Order Successor is the smallest number that is still greater than 50. To find it: go to the Right subtree (70), then go all the way Left.',
        },
        {
          stepNumber: 3,
          totalSteps: 6,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          activeNodeId: 'node-60',
          correctNodeIds: ['node-60'],
          nodeLabels: { 'node-50': 'TARGET', 'node-60': 'SUCCESSOR (60)' },
          comparisonBanner: { text: 'Smallest in Right Subtree = 60', subtext: '60 is the perfect replacement value!', direction: 'FOUND' },
          title: 'Step 3: Identify Successor (60)',
          explanation: 'In 70\'s subtree, the leftmost node is 60. Node 60 is greater than everything on the left, but smaller than everything else on the right!',
        },
        {
          stepNumber: 4,
          totalSteps: 6,
          treeValues: [50, 30, 70, 20, 40, 60, 80],
          activeNodeId: 'node-50',
          highlightedNodeIds: ['node-60'],
          nodeLabels: { 'node-50': 'COPY 60 HERE', 'node-60': 'ORIGINAL (60)' },
          comparisonBanner: { text: 'Copy Successor Value 60 into Target Node', subtext: 'Overwrite value 50 with value 60', direction: 'REPLACE' },
          title: 'Step 4: Overwrite Target Value with 60',
          explanation: 'Copy the value 60 into the root node. The root node now holds value 60.',
        },
        {
          stepNumber: 5,
          totalSteps: 6,
          treeValues: [60, 30, 70, 20, 40, 80],
          correctNodeIds: ['node-60'],
          nodeLabels: { 'node-60': 'NEW ROOT (60)', 'node-70': 'RIGHT PARENT' },
          comparisonBanner: { text: 'Delete Original Successor Leaf (60)', subtext: 'Successor is always a leaf or has at most 1 child', direction: 'DELETE' },
          title: 'Step 5: Delete Original Successor Node',
          explanation: 'Now delete the original node 60 from the bottom of the right subtree (which is easy because it is a leaf).',
        },
        {
          stepNumber: 6,
          totalSteps: 6,
          treeValues: [60, 30, 70, 20, 40, 80],
          correctNodeIds: ['node-60', 'node-30', 'node-70', 'node-20', 'node-40', 'node-80'],
          comparisonBanner: { text: '✓ 2-Child Deletion Successfully Solved!', subtext: 'Root is 60: all left < 60, all right > 60', direction: 'INFO' },
          title: 'Step 6: Final Valid BST Verified',
          explanation: 'The tree is 100% valid! Left subtree: {20, 30, 40} are all < 60. Right subtree: {70, 80} are all > 60. Mastered!',
        },
      ];

    case 15: // Inorder Traversal
      return [
        {
          stepNumber: 1,
          totalSteps: 5,
          treeValues: [40, 20, 60, 10, 30, 50, 70],
          nodeLabels: { 'node-40': 'ROOT' },
          comparisonBanner: { text: 'Inorder Formula: Left → Root → Right', subtext: 'In BST, Inorder ALWAYS produces SORTED order!', direction: 'INFO' },
          title: 'Step 1: Understand Inorder Traversal',
          explanation: 'Inorder visits the Left subtree first, then the current Node, then the Right subtree. In a BST, this yields numbers in ascending order.',
        },
        {
          stepNumber: 2,
          totalSteps: 5,
          treeValues: [40, 20, 60, 10, 30, 50, 70],
          highlightedNodeIds: ['node-10', 'node-20', 'node-30'],
          nodeLabels: { 'node-10': '1st (10)', 'node-20': '2nd (20)', 'node-30': '3rd (30)' },
          comparisonBanner: { text: 'Step A: Traverse Left Subtree [10, 20, 30]', subtext: 'Leftmost leaf 10, then parent 20, then right child 30', direction: 'LEFT' },
          title: 'Step 2: Visit Left Subtree',
          explanation: 'Go all the way left: visit 10 → backtrack to 20 → visit right child 30.',
        },
        {
          stepNumber: 3,
          totalSteps: 5,
          treeValues: [40, 20, 60, 10, 30, 50, 70],
          activeNodeId: 'node-40',
          correctNodeIds: ['node-10', 'node-20', 'node-30'],
          nodeLabels: { 'node-40': '4th: ROOT (40)' },
          comparisonBanner: { text: 'Step B: Visit Root Node (40)', subtext: 'Visited so far: [10, 20, 30, 40]', direction: 'INFO' },
          title: 'Step 3: Visit Root Node (40)',
          explanation: 'After finishing the entire left subtree, visit root node 40.',
        },
        {
          stepNumber: 4,
          totalSteps: 5,
          treeValues: [40, 20, 60, 10, 30, 50, 70],
          highlightedNodeIds: ['node-50', 'node-60', 'node-70'],
          nodeLabels: { 'node-50': '5th (50)', 'node-60': '6th (60)', 'node-70': '7th (70)' },
          comparisonBanner: { text: 'Step C: Traverse Right Subtree [50, 60, 70]', subtext: 'Leftmost 50, then parent 60, then right leaf 70', direction: 'RIGHT' },
          title: 'Step 4: Visit Right Subtree',
          explanation: 'Traverse right: visit 50 → parent 60 → right child 70.',
        },
        {
          stepNumber: 5,
          totalSteps: 5,
          treeValues: [40, 20, 60, 10, 30, 50, 70],
          correctNodeIds: ['node-10', 'node-20', 'node-30', 'node-40', 'node-50', 'node-60', 'node-70'],
          comparisonBanner: { text: 'Result: [10, 20, 30, 40, 50, 60, 70]', subtext: 'Perfect strictly ascending sorted sequence!', direction: 'INFO' },
          title: 'Step 5: Full Inorder Sequence',
          explanation: 'Result is [10, 20, 30, 40, 50, 60, 70]. Notice how they are perfectly sorted from smallest to largest.',
        },
      ];

    case 19: // Finding Minimum
      return [
        {
          stepNumber: 1,
          totalSteps: 3,
          treeValues: [50, 30, 70, 20, 40, 10],
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'START' },
          comparisonBanner: { text: 'Find Minimum: Start at Root 50', subtext: 'Rule: Smaller values are always to the LEFT', direction: 'LEFT' },
          title: 'Step 1: Start at Root',
          explanation: 'Because every left branch holds smaller numbers, the smallest value in the entire tree is the leftmost node.',
        },
        {
          stepNumber: 2,
          totalSteps: 3,
          treeValues: [50, 30, 70, 20, 40, 10],
          activeNodeId: 'node-30',
          highlightedNodeIds: ['node-20'],
          nodeLabels: { 'node-30': 'GO LEFT', 'node-20': 'GO LEFT' },
          comparisonBanner: { text: 'Follow Left Pointers: 50 → 30 → 20 → 10', subtext: 'Keep going left until node.left == null', direction: 'LEFT' },
          title: 'Step 2: Traverse Leftwards',
          explanation: 'From 50 go left to 30, from 30 go left to 20, from 20 go left to 10.',
        },
        {
          stepNumber: 3,
          totalSteps: 3,
          treeValues: [50, 30, 70, 20, 40, 10],
          correctNodeIds: ['node-10'],
          nodeLabels: { 'node-10': 'MINIMUM (10)' },
          comparisonBanner: { text: 'Minimum = 10 (Leftmost Node)', subtext: '10 has no left child → Minimum reached in O(h) time', direction: 'FOUND' },
          title: 'Step 3: Minimum Reached',
          explanation: 'Node 10 has no left child (left is null). Therefore, 10 is the absolute Minimum value in this BST.',
        },
      ];

    case 20: // Finding Maximum
      return [
        {
          stepNumber: 1,
          totalSteps: 3,
          treeValues: [50, 30, 70, 60, 90, 95],
          activeNodeId: 'node-50',
          nodeLabels: { 'node-50': 'START' },
          comparisonBanner: { text: 'Find Maximum: Start at Root 50', subtext: 'Rule: Greater values are always to the RIGHT', direction: 'RIGHT' },
          title: 'Step 1: Start at Root',
          explanation: 'Because every right branch holds greater numbers, the largest value in the tree is the rightmost node.',
        },
        {
          stepNumber: 2,
          totalSteps: 3,
          treeValues: [50, 30, 70, 60, 90, 95],
          activeNodeId: 'node-70',
          highlightedNodeIds: ['node-90'],
          nodeLabels: { 'node-70': 'GO RIGHT', 'node-90': 'GO RIGHT' },
          comparisonBanner: { text: 'Follow Right Pointers: 50 → 70 → 90 → 95', subtext: 'Keep going right until node.right == null', direction: 'RIGHT' },
          title: 'Step 2: Traverse Rightwards',
          explanation: 'From 50 go right to 70, from 70 go right to 90, from 90 go right to 95.',
        },
        {
          stepNumber: 3,
          totalSteps: 3,
          treeValues: [50, 30, 70, 60, 90, 95],
          correctNodeIds: ['node-95'],
          nodeLabels: { 'node-95': 'MAXIMUM (95)' },
          comparisonBanner: { text: 'Maximum = 95 (Rightmost Node)', subtext: '95 has no right child → Maximum reached in O(h) time', direction: 'FOUND' },
          title: 'Step 3: Maximum Reached',
          explanation: 'Node 95 has no right child. Therefore, 95 is the absolute Maximum value in this BST.',
        },
      ];

    // Default fallback generator for any topic
    default: {
      return [
        {
          stepNumber: 1,
          totalSteps: 3,
          treeValues: [40, 20, 60],
          activeNodeId: 'node-40',
          nodeLabels: { 'node-40': 'ROOT' },
          comparisonBanner: { text: 'Examine Top Level: Root Node', subtext: 'Start analysis at the root of the tree', direction: 'INFO' },
          title: 'Step 1: Identify Reference Node',
          explanation: 'We begin by inspecting the top of the tree structure.',
        },
        {
          stepNumber: 2,
          totalSteps: 3,
          treeValues: [40, 20, 60],
          highlightedNodeIds: ['node-20', 'node-60'],
          nodeLabels: { 'node-20': 'LEFT (< 40)', 'node-60': 'RIGHT (> 40)' },
          comparisonBanner: { text: 'Compare Left & Right Branches', subtext: 'Left is smaller, Right is greater', direction: 'INFO' },
          title: 'Step 2: Check Branching Rules',
          explanation: 'Examine how child nodes relate to their parent according to BST rules.',
        },
        {
          stepNumber: 3,
          totalSteps: 3,
          treeValues: [40, 20, 60],
          correctNodeIds: ['node-40', 'node-20', 'node-60'],
          comparisonBanner: { text: 'Concept Applied Successfully', subtext: 'Ready for interactive micro-practice below!', direction: 'INFO' },
          title: 'Step 3: Concept Verified',
          explanation: 'The concept is fully visualised. Now try the interactive practice below to solidify your understanding!',
        },
      ];
    }
  }
}
