import { TopicAnimationData } from './types';

export const TOPICS_TRAVERSALS: Record<number, TopicAnimationData> = {
  // Topic 20: In-order Traversal
  20: {
    topicNumber: 20,
    topicTitle: 'In-order Traversal',
    shortTitle: 'In-order',
    rule: 'Left → Root → Right (Yields Sorted Ascending Order)',
    totalSteps: 7,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Go to the left subtree.',
        why: 'In-order traversal starts at the root and descends left first.',
        banner: { text: 'Rule: Left → Root → Right', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Go to the left subtree',
        shortSentence: 'Go to the left subtree.',
        currentStep: 'Go to the left subtree.',
        whatNext: 'Visit the left node.',
        why: 'Left subtree must be fully processed before root.',
        banner: { text: 'Descend to Left Subtree {20, 30, 40}', subtext: 'Following left pointer', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'L-ROOT: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Visit the left node',
        shortSentence: 'Visit the left node (20).',
        currentStep: 'Visit the left node (20).',
        whatNext: 'Visit the root of this subtree.',
        why: 'Node 20 is the leftmost leaf, so it is visited first.',
        banner: { text: 'Visit Node [ 20 ]', subtext: 'Output: [20]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: '1st: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [20],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Visit the root of the subtree and then the global root',
        shortSentence: 'Visit the subtree root (30) and its right child (40).',
        currentStep: 'Visit the subtree root (30) and its right child (40).',
        whatNext: 'Visit the main tree root (50).',
        why: 'In-order rule processes Left (20) → Root (30) → Right (40).',
        banner: { text: 'Visit Node [ 30 ] then [ 40 ]', subtext: 'Output: [20, 30, 40]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: '2nd: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: '3rd: 40' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 30, 40],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Visit the root',
        shortSentence: 'Visit the main tree root (50).',
        currentStep: 'Visit the main tree root (50).',
        whatNext: 'Go to the right subtree.',
        why: 'Left subtree is completely finished, so we visit root 50.',
        banner: { text: 'Visit Root Node [ 50 ]', subtext: 'Output: [20, 30, 40, 50]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: '4th: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'NEXT' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 30, 40, 50],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Go to the right subtree and repeat',
        shortSentence: 'Go to the right subtree and visit node 70.',
        currentStep: 'Go to the right subtree and visit node 70.',
        whatNext: 'Get final sorted sequence.',
        why: 'Repeat Left → Root → Right on the right subtree.',
        banner: { text: 'Visit Node [ 70 ]', subtext: 'Output: [20, 30, 40, 50, 70]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: '5th: 70' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 30, 40, 50, 70],
      },
      {
        stepIndex: 6,
        title: 'Step 7: Get the final sorted sequence',
        shortSentence: 'Get the final sorted sequence: [ 20, 30, 40, 50, 70 ].',
        currentStep: 'Get the final sorted sequence: [ 20, 30, 40, 50, 70 ].',
        whatNext: 'In-order traversal complete.',
        why: 'In-order traversal of any BST always outputs nodes in sorted ascending order.',
        banner: { text: '✓ In-Order = Sorted Ascending Sequence', subtext: '[ 20, 30, 40, 50, 70 ]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 30, 40, 50, 70],
      },
    ],
  },

  // Topic 21: Pre-order Traversal
  21: {
    topicNumber: 21,
    topicTitle: 'Pre-order Traversal',
    shortTitle: 'Pre-order',
    rule: 'Root → Left → Right (Root Visited FIRST)',
    totalSteps: 7,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Visit the root immediately.',
        why: 'Pre-order visits the root BEFORE traversing children.',
        banner: { text: 'Rule: Root → Left → Right', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Visit the root',
        shortSentence: 'Visit the root (50) first.',
        currentStep: 'Visit the root (50) first.',
        whatNext: 'Go to the left subtree.',
        why: 'Root 50 is appended to output first.',
        banner: { text: 'Visit Root [ 50 ]', subtext: 'Output: [50]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: '1st: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'NEXT: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [50],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Go to the left subtree',
        shortSentence: 'Go to the left subtree and visit node 30.',
        currentStep: 'Go to the left subtree and visit node 30.',
        whatNext: 'Visit the left node.',
        why: '30 is the root of the left subtree, so it is visited next.',
        banner: { text: 'Visit Subtree Root [ 30 ]', subtext: 'Output: [50, 30]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: '2nd: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'NEXT: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [50, 30],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Visit the left node',
        shortSentence: 'Visit the left child (20) and then right child (40).',
        currentStep: 'Visit the left child (20) and then right child (40).',
        whatNext: 'Go to the right subtree.',
        why: 'Following Root (30) → Left (20) → Right (40).',
        banner: { text: 'Visit [ 20 ] then [ 40 ]', subtext: 'Output: [50, 30, 20, 40]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: '3rd: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: '4th: 40' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [50, 30, 20, 40],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Go to the right subtree',
        shortSentence: 'Go to the right subtree.',
        currentStep: 'Go to the right subtree.',
        whatNext: 'Visit node 70.',
        why: 'Left subtree is fully finished.',
        banner: { text: 'Move to Right Subtree {70}', subtext: 'Following right branch', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'NEXT: 70' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [50, 30, 20, 40],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Repeat for every subtree',
        shortSentence: 'Repeat for every subtree: visit root 70.',
        currentStep: 'Repeat for every subtree: visit root 70.',
        whatNext: 'Get the final sequence.',
        why: 'Node 70 is visited as root of right subtree.',
        banner: { text: 'Visit Node [ 70 ]', subtext: 'Output: [50, 30, 20, 40, 70]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: '5th: 70' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [50, 30, 20, 40, 70],
      },
      {
        stepIndex: 6,
        title: 'Step 7: Get the final sequence',
        shortSentence: 'Get the final sequence: [ 50, 30, 20, 40, 70 ].',
        currentStep: 'Get the final sequence: [ 50, 30, 20, 40, 70 ].',
        whatNext: 'Pre-order complete.',
        why: 'Useful for serializing and cloning trees.',
        banner: { text: '✓ Pre-order Complete: [ 50, 30, 20, 40, 70 ]', subtext: 'Root always appears first', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [50, 30, 20, 40, 70],
      },
    ],
  },

  // Topic 22: Post-order Traversal
  22: {
    topicNumber: 22,
    topicTitle: 'Post-order Traversal',
    shortTitle: 'Post-order',
    rule: 'Left → Right → Root (Root Visited LAST)',
    totalSteps: 8,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Go to the left subtree.',
        why: 'Post-order must process all children before visiting root.',
        banner: { text: 'Rule: Left → Right → Root', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Go to the left subtree',
        shortSentence: 'Go to the left subtree.',
        currentStep: 'Go to the left subtree.',
        whatNext: 'Visit the left subtree.',
        why: 'Descend to leftmost leaf first.',
        banner: { text: 'Descend to Left Subtree', subtext: 'Visiting left leaf first', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'SUBTREE ROOT' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Visit the left subtree',
        shortSentence: 'Visit the left leaf (20).',
        currentStep: 'Visit the left leaf (20).',
        whatNext: 'Go to the right subtree.',
        why: 'Node 20 is processed first.',
        banner: { text: 'Visit Node [ 20 ]', subtext: 'Output: [20]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: '1st: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'highlight' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
        traversalOutput: [20],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Go to the right subtree of 30',
        shortSentence: 'Visit the right leaf (40) and then parent (30).',
        currentStep: 'Visit the right leaf (40) and then parent (30).',
        whatNext: 'Go to the right subtree of root.',
        why: 'Left (20) → Right (40) → Root (30).',
        banner: { text: 'Visit [ 40 ] then [ 30 ]', subtext: 'Output: [20, 40, 30]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: '3rd: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: '2nd: 40' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 40, 30],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Go to the right subtree',
        shortSentence: 'Go to the right subtree of the root.',
        currentStep: 'Go to the right subtree of the root.',
        whatNext: 'Visit the right subtree.',
        why: 'Entire left subtree is done; now process right subtree.',
        banner: { text: 'Move to Right Subtree {70}', subtext: 'Before visiting root 50', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'RIGHT SUBTREE' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 40, 30],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Visit the right subtree',
        shortSentence: 'Visit node 70 in the right subtree.',
        currentStep: 'Visit node 70 in the right subtree.',
        whatNext: 'Visit the root.',
        why: 'Node 70 has no children, so it is visited.',
        banner: { text: 'Visit Node [ 70 ]', subtext: 'Output: [20, 40, 30, 70]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: '4th: 70' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 40, 30, 70],
      },
      {
        stepIndex: 6,
        title: 'Step 7: Visit the root',
        shortSentence: 'Visit the root (50) last.',
        currentStep: 'Visit the root (50) last.',
        whatNext: 'Get the final sequence.',
        why: 'Both left and right children are done, so root 50 is visited last.',
        banner: { text: 'Visit Root [ 50 ] Last', subtext: 'Output: [20, 40, 30, 70, 50]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: '5th: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 40, 30, 70, 50],
      },
      {
        stepIndex: 7,
        title: 'Step 8: Get the final sequence',
        shortSentence: 'Get the final sequence: [ 20, 40, 30, 70, 50 ].',
        currentStep: 'Get the final sequence: [ 20, 40, 30, 70, 50 ].',
        whatNext: 'Post-order complete.',
        why: 'Post-order is ideal for bottom-up tree deletion and expression evaluation.',
        banner: { text: '✓ Post-order Complete: [ 20, 40, 30, 70, 50 ]', subtext: 'Root always appears last', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
        traversalOutput: [20, 40, 30, 70, 50],
      },
    ],
  },

  // Topic 23: Level-order Traversal (BFS)
  23: {
    topicNumber: 23,
    topicTitle: 'Level-order Traversal (BFS)',
    shortTitle: 'Level-order',
    rule: 'Queue: FIFO (Level 0 → Level 1 → Level 2)',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Put the root node into a queue',
        shortSentence: 'Put the root node (50) into a queue.',
        currentStep: 'Put the root node (50) into a queue.',
        whatNext: 'Remove front node and visit it.',
        why: 'A queue ensures nodes are visited level-by-level.',
        banner: { text: 'Queue: [ 50 ]', subtext: 'Level 0 queued', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'QUEUED: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
        traversalOutput: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Remove the front node and visit it',
        shortSentence: 'Remove front node (50) from queue and visit it.',
        currentStep: 'Remove front node (50) from queue and visit it.',
        whatNext: 'Add its left and right children.',
        why: 'Node 50 is level 0 output.',
        banner: { text: 'Visit Node [ 50 ] (Level 0)', subtext: 'Output: [50]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'VISITED (50)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'ENQUEUE' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'ENQUEUE' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
        traversalOutput: [50],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Add its left and right children to the queue',
        shortSentence: 'Add children 30 and 70 to the queue, then visit them.',
        currentStep: 'Add children 30 and 70 to the queue, then visit them.',
        whatNext: 'Add next level children.',
        why: 'Level 1 contains nodes 30 and 70.',
        banner: { text: 'Visit Level 1: [ 30, 70 ]', subtext: 'Output: [50, 30, 70]', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'VISITED (30)' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'VISITED (70)' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'ENQUEUE' },
          { id: '80', value: 80, x: 410, y: 180, state: 'active', badge: 'ENQUEUE' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
        traversalOutput: [50, 30, 70],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Repeat until the queue is empty',
        shortSentence: 'Repeat for Level 2 nodes (20 and 80) until queue is empty.',
        currentStep: 'Repeat for Level 2 nodes (20 and 80) until queue is empty.',
        whatNext: 'Get final level sequence.',
        why: 'All nodes have now been visited in breadth-first order.',
        banner: { text: 'Visit Level 2: [ 20, 80 ]', subtext: 'Queue is now empty', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'VISITED (20)' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found', badge: 'VISITED (80)' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
        traversalOutput: [50, 30, 70, 20, 80],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Get the level-by-level sequence',
        shortSentence: 'Get the level-by-level sequence: [ 50, 30, 70, 20, 80 ].',
        currentStep: 'Get the level-by-level sequence: [ 50, 30, 70, 20, 80 ].',
        whatNext: 'Level-order traversal complete.',
        why: 'BFS visits row by row from top to bottom.',
        banner: { text: '✓ BFS Complete: [ 50, 30, 70, 20, 80 ]', subtext: 'Visited top-to-bottom, left-to-right', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
        traversalOutput: [50, 30, 70, 20, 80],
      },
    ],
  },

  // Topic 24: Validating a BST
  24: {
    topicNumber: 24,
    topicTitle: 'Validating a BST',
    shortTitle: 'Validate BST',
    rule: 'Min Bound < Node Value < Max Bound',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root with a valid range of (-∞, +∞)',
        shortSentence: 'Start at the root with a valid range of (-∞, +∞).',
        currentStep: 'Start at the root with a valid range of (-∞, +∞).',
        whatNext: 'Update range for left child.',
        why: 'The root can hold any initial value.',
        comparisonFormula: '-∞ < 50 < +∞ → Valid',
        banner: { text: 'Root (50): Allowed Range (-∞, +∞)', subtext: '50 is in range ✓', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: '(-∞, +∞)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: For the left child, update the upper bound to the current node',
        shortSentence: 'For the left child (30), update the upper bound to 50: (-∞, 50).',
        currentStep: 'For the left child (30), update the upper bound to 50: (-∞, 50).',
        whatNext: 'Check if 30 is in range.',
        why: 'Left subtree elements must all be strictly less than 50.',
        comparisonFormula: '-∞ < 30 < 50 → Valid ✓',
        banner: { text: 'Left Child (30): Allowed (-∞, 50)', subtext: '30 < 50 ✓', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: '(-∞, 50)' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: For the right child, update the lower bound to the current node',
        shortSentence: 'For the right child (70), update the lower bound to 50: (50, +∞).',
        currentStep: 'For the right child (70), update the lower bound to 50: (50, +∞).',
        whatNext: 'Check if 70 is in range.',
        why: 'Right subtree elements must all be strictly greater than 50.',
        comparisonFormula: '50 < 70 < +∞ → Valid ✓',
        banner: { text: 'Right Child (70): Allowed (50, +∞)', subtext: '70 > 50 ✓', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: '(50, +∞)' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Check if every node value lies strictly within its allowed range',
        shortSentence: 'Check if every node value lies strictly within its allowed range.',
        currentStep: 'Check if every node value lies strictly within its allowed range.',
        whatNext: 'Confirm overall tree validity.',
        why: 'Both 30 and 70 satisfy their respective boundary intervals.',
        banner: { text: 'All Nodes Pass Boundary Checks', subtext: 'No illegal values found', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: If all nodes pass, the tree is a valid BST',
        shortSentence: 'If all nodes pass, the tree is a valid BST.',
        currentStep: 'If all nodes pass, the tree is a valid BST.',
        whatNext: 'Validation complete.',
        why: 'The tree satisfies the BST invariant globally.',
        banner: { text: '✓ Tree is 100% a Valid BST', subtext: 'O(N) validation passed', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'VALID' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'VALID' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'VALID' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 25: Time & Space Complexity
  25: {
    topicNumber: 25,
    topicTitle: 'Time & Space Complexity',
    shortTitle: 'Complexity',
    rule: 'Balanced: O(log N) | Skewed: O(N) | Space: O(h)',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: In a balanced BST, each step cuts remaining nodes in half',
        shortSentence: 'In a balanced BST, each comparison cuts the remaining search space in half.',
        currentStep: 'In a balanced BST, each comparison cuts the remaining search space in half.',
        whatNext: 'Derive logarithmic time.',
        why: 'Binary choices eliminate one full subtree at each step.',
        comparisonFormula: 'N → N/2 → N/4 → ... → 1 = log₂(N) steps',
        banner: { text: 'Balanced BST: Eliminates 50% per Step', subtext: 'Halving search space', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'N NODES' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight', badge: 'N/2 NODES' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed', label: 'Discarded' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Searching, inserting, and deleting take O(log N) time',
        shortSentence: 'Searching, inserting, and deleting take O(log N) time in balanced trees.',
        currentStep: 'Searching, inserting, and deleting take O(log N) time in balanced trees.',
        whatNext: 'Compare with worst-case skewed tree.',
        why: 'Height of balanced BST is log₂(N).',
        banner: { text: 'Average Time: O(log N)', subtext: 'Search, Insert, Delete = O(h)', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'O(log N)' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'O(log N)' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: In a skewed tree, operations take O(N) time like a linked list',
        shortSentence: 'In a skewed tree, operations take O(N) time like a linked list.',
        currentStep: 'In a skewed tree, operations take O(N) time like a linked list.',
        whatNext: 'Keep trees balanced.',
        why: 'When tree degrades to a chain, height becomes N.',
        banner: { text: 'Worst-Case Time: O(N)', subtext: 'Skewed chain without balancing', type: 'WARNING' },
        nodes: [
          { id: '10', value: 10, x: 200, y: 40, state: 'warning', badge: '1' },
          { id: '20', value: 20, x: 250, y: 110, state: 'warning', badge: '2' },
          { id: '30', value: 30, x: 300, y: 180, state: 'warning', badge: 'N' },
        ],
        edges: [
          { fromId: '10', toId: '20', state: 'active' },
          { fromId: '20', toId: '30', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Keeping the tree balanced ensures optimal speed',
        shortSentence: 'Keeping the tree balanced ensures optimal O(log N) speed and O(h) space.',
        currentStep: 'Keeping the tree balanced ensures optimal O(log N) speed and O(h) space.',
        whatNext: 'Complexity summarized.',
        why: 'AVL and Red-Black trees auto-balance to maintain O(log N).',
        banner: { text: '✓ Complexity: O(log N) Time, O(h) Auxiliary Space', subtext: 'Balanced trees are optimal', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'OPTIMAL' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 26: BST vs Array vs Linked List
  26: {
    topicNumber: 26,
    topicTitle: 'BST vs Array vs Linked List',
    shortTitle: 'BST vs Array vs LL',
    rule: 'BST combines fast search O(log N) and fast insert O(log N)',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Arrays provide instant lookups but slow insertions',
        shortSentence: 'Arrays provide fast lookup O(1) / O(log N) but slow insertion O(N).',
        currentStep: 'Arrays provide fast lookup O(1) / O(log N) but slow insertion O(N).',
        whatNext: 'Examine linked lists.',
        why: 'Inserting into an array requires shifting elements.',
        banner: { text: 'Array: Lookup O(1), Insert O(N)', subtext: 'Slow insertions', type: 'INFO' },
        nodes: [
          { id: 'A', value: 10, x: 180, y: 60, state: 'default', label: '[0]' },
          { id: 'B', value: 20, x: 260, y: 60, state: 'default', label: '[1]' },
          { id: 'C', value: 30, x: 340, y: 60, state: 'default', label: '[2]' },
        ],
        edges: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Linked lists allow quick insertions but slow searches',
        shortSentence: 'Linked lists allow quick insertion O(1) but slow search O(N).',
        currentStep: 'Linked lists allow quick insertion O(1) but slow search O(N).',
        whatNext: 'Compare with BST.',
        why: 'Linked lists have no random access or binary search.',
        banner: { text: 'Linked List: Insert O(1), Search O(N)', subtext: 'Slow sequential search', type: 'INFO' },
        nodes: [
          { id: 'L1', value: 10, x: 180, y: 120, state: 'default' },
          { id: 'L2', value: 20, x: 260, y: 120, state: 'default' },
          { id: 'L3', value: 30, x: 340, y: 120, state: 'default' },
        ],
        edges: [
          { fromId: 'L1', toId: 'L2', state: 'active' },
          { fromId: 'L2', toId: 'L3', state: 'active' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: BST combines fast search and fast insertion in O(log N)',
        shortSentence: 'BST combines fast search and fast insertion in O(log N).',
        currentStep: 'BST combines fast search and fast insertion in O(log N).',
        whatNext: 'Confirm why BST is superior.',
        why: 'BST gives logarithmic performance for all core operations.',
        banner: { text: 'BST: Search O(log N), Insert O(log N)', subtext: 'Best of both worlds', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'BST: O(log N)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: BST provides the best balance for dynamic sorted data',
        shortSentence: 'BST provides the best balance for dynamic sorted data.',
        currentStep: 'BST provides the best balance for dynamic sorted data.',
        whatNext: 'All 26 topics mastered.',
        why: 'BST powers database indexes, search engines, and sorting systems.',
        banner: { text: '✓ BST Wins for Dynamic Sorted Datasets', subtext: 'Foundation of modern computing', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'BEST CHOICE' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },
};
