import { TopicAnimationData } from './types';

export const TOPICS_BASICS: Record<number, TopicAnimationData> = {
  // Topic 1: What is a Tree?
  1: {
    topicNumber: 1,
    topicTitle: 'What is a Tree?',
    shortTitle: 'Tree Basics',
    rule: 'Hierarchical Structure (No Loops)',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start with the root node',
        shortSentence: 'Start at the single root node at the top.',
        currentStep: 'Start at the single root node at the top.',
        whatNext: 'Follow branches down to child nodes.',
        why: 'Every tree has exactly one entry point called the root.',
        banner: { text: 'Entry Point: Root Node (40)', subtext: 'No parent above it', type: 'INFO' },
        nodes: [
          { id: '40', value: 40, x: 270, y: 50, state: 'active', badge: 'ROOT' },
          { id: '20', value: 20, x: 170, y: 130, state: 'dimmed' },
          { id: '60', value: 60, x: 370, y: 130, state: 'dimmed' },
        ],
        edges: [
          { fromId: '40', toId: '20', state: 'dimmed' },
          { fromId: '40', toId: '60', state: 'dimmed' },
        ],
        prediction: {
          question: 'What is the topmost node with no parent called?',
          options: ['Root Node', 'Leaf Node', 'Branch Pointer'],
          correctIndex: 0,
          hint: 'Think of the top starting point of the upside-down tree.',
          explanation: 'The Root is the single top-level node where all tree operations start.',
        },
      },
      {
        stepIndex: 1,
        title: 'Step 2: Follow the edges (branches)',
        shortSentence: 'Follow the connecting lines (edges) down to the children.',
        currentStep: 'Follow the connecting lines (edges) down to the children.',
        whatNext: 'Check the bottom nodes.',
        why: 'Edges connect parents to their children.',
        banner: { text: 'Branches (Edges) Connect Downward', subtext: '40 connects to 20 & 60', type: 'INFO' },
        nodes: [
          { id: '40', value: 40, x: 270, y: 50, state: 'highlight', badge: 'PARENT' },
          { id: '20', value: 20, x: 170, y: 130, state: 'active', badge: 'CHILD' },
          { id: '60', value: 60, x: 370, y: 130, state: 'active', badge: 'CHILD' },
        ],
        edges: [
          { fromId: '40', toId: '20', state: 'active' },
          { fromId: '40', toId: '60', state: 'active' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Reach the leaf nodes',
        shortSentence: 'Reach the bottom nodes that have no children.',
        currentStep: 'Reach the bottom nodes that have no children.',
        whatNext: 'Confirm the tree has no closed loops.',
        why: 'Nodes with 0 children are called leaves.',
        banner: { text: 'Bottom Nodes = Leaves', subtext: '0 children attached', type: 'SUCCESS' },
        nodes: [
          { id: '40', value: 40, x: 270, y: 50, state: 'default' },
          { id: '20', value: 20, x: 170, y: 130, state: 'active', badge: 'LEAF', showNullLeft: true, showNullRight: true },
          { id: '60', value: 60, x: 370, y: 130, state: 'active', badge: 'LEAF', showNullLeft: true, showNullRight: true },
        ],
        edges: [
          { fromId: '40', toId: '20', state: 'default' },
          { fromId: '40', toId: '60', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Tree structure complete',
        shortSentence: 'Confirm the hierarchy is connected with no loops or cycles.',
        currentStep: 'Confirm the hierarchy is connected with no loops or cycles.',
        whatNext: 'Ready for binary trees.',
        why: 'Trees are connected and acyclic graphs.',
        banner: { text: 'Tree Valid & Complete', subtext: 'Hierarchical and cycle-free', type: 'SUCCESS' },
        nodes: [
          { id: '40', value: 40, x: 270, y: 50, state: 'found', badge: 'ROOT' },
          { id: '20', value: 20, x: 170, y: 130, state: 'found', badge: 'LEAF' },
          { id: '60', value: 60, x: 370, y: 130, state: 'found', badge: 'LEAF' },
        ],
        edges: [
          { fromId: '40', toId: '20', state: 'default' },
          { fromId: '40', toId: '60', state: 'default' },
        ],
      },
    ],
  },

  // Topic 2: What is a Binary Tree?
  2: {
    topicNumber: 2,
    topicTitle: 'What is a Binary Tree?',
    shortTitle: 'Binary Tree',
    rule: 'At most 2 children per node (0, 1, or 2)',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start with a single root node',
        shortSentence: 'Start with a root node that currently has 0 children.',
        currentStep: 'Start with a root node that currently has 0 children.',
        whatNext: 'Attach a left child.',
        why: 'Every binary tree node can hold 0, 1, or 2 children.',
        banner: { text: '0 of 2 Children Used', subtext: 'Valid binary node', type: 'INFO' },
        nodes: [{ id: '50', value: 50, x: 270, y: 60, state: 'active', badge: '0 CH' }],
        edges: [],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Add at most one left child',
        shortSentence: 'Attach node 30 as the left child of node 50.',
        currentStep: 'Attach node 30 as the left child of node 50.',
        whatNext: 'Attach a right child.',
        why: 'Node 50 now has 1 child out of 2 allowed.',
        banner: { text: '1 of 2 Children Used', subtext: 'Left child attached', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 60, state: 'highlight', badge: '1 CH' },
          { id: '30', value: 30, x: 170, y: 140, state: 'active', badge: 'LEFT' },
        ],
        edges: [{ fromId: '50', toId: '30', state: 'active' }],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Add at most one right child',
        shortSentence: 'Attach node 70 as the right child to reach full capacity.',
        currentStep: 'Attach node 70 as the right child to reach full capacity.',
        whatNext: 'Verify the binary rule across the tree.',
        why: 'Node 50 now has its maximum limit of 2 children.',
        banner: { text: '2 of 2 Children (FULL)', subtext: 'Maximum children reached', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 60, state: 'found', badge: '2 CH' },
          { id: '30', value: 30, x: 170, y: 140, state: 'active', badge: 'LEFT' },
          { id: '70', value: 70, x: 370, y: 140, state: 'active', badge: 'RIGHT' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
        ],
        prediction: {
          question: 'Can node 50 have a 3rd child attached directly to it?',
          options: ['No, maximum is 2 children in a Binary Tree', 'Yes, anywhere', 'Yes, only in the middle'],
          correctIndex: 0,
          hint: 'Remember the prefix "Bi-" means two.',
          explanation: 'Binary trees strictly allow only 0, 1, or 2 children per node.',
        },
      },
      {
        stepIndex: 3,
        title: 'Step 4: Each node has 0, 1, or 2 children',
        shortSentence: 'Check that every node in the tree has at most 2 children.',
        currentStep: 'Check that every node in the tree has at most 2 children.',
        whatNext: 'Ready for Binary Search Tree ordering.',
        why: 'All nodes satisfy the binary condition.',
        banner: { text: '✓ Binary Tree Rules Satisfied', subtext: 'All nodes have ≤ 2 children', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 60, state: 'found', badge: '2 CH' },
          { id: '30', value: 30, x: 170, y: 140, state: 'found', badge: '0 CH' },
          { id: '70', value: 70, x: 370, y: 140, state: 'found', badge: '0 CH' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 3: What is a Binary Search Tree (BST)?
  3: {
    topicNumber: 3,
    topicTitle: 'What is a Binary Search Tree (BST)?',
    shortTitle: 'BST Basics',
    rule: 'Left < Root < Right',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start with the root node',
        shortSentence: 'Start with the root node (50).',
        currentStep: 'Start with the root node (50).',
        whatNext: 'Compare incoming values with 50.',
        why: 'The root node is the baseline comparison value.',
        banner: { text: 'Start with Root Node (50)', subtext: 'Reference for all values', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 50, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 170, y: 130, state: 'dimmed' },
          { id: '70', value: 70, x: 370, y: 130, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Compare the new value with the root',
        shortSentence: 'Compare the new value with the root node.',
        currentStep: 'Compare the new value with the root node.',
        whatNext: 'Decide left or right.',
        why: 'Comparison determines which branch to take.',
        banner: { text: 'Compare New Value with Root', subtext: 'Is it smaller or larger?', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 50, state: 'highlight', badge: 'COMPARE' },
          { id: '30', value: 30, x: 170, y: 130, state: 'dimmed' },
          { id: '70', value: 70, x: 370, y: 130, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Smaller values go to the left',
        shortSentence: 'Smaller values go to the left.',
        currentStep: 'Smaller values go to the left.',
        whatNext: 'Check larger values on the right.',
        why: '30 is smaller than 50, so it belongs on the left.',
        comparisonFormula: '30 < 50 → Go Left',
        banner: { text: '30 < 50 → Goes on the LEFT', subtext: 'BST Left rule', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 50, state: 'default' },
          { id: '30', value: 30, x: 170, y: 130, state: 'active', badge: 'LEFT: 30 < 50' },
          { id: '70', value: 70, x: 370, y: 130, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Larger values go to the right',
        shortSentence: 'Larger values go to the right.',
        currentStep: 'Larger values go to the right.',
        whatNext: 'Verify until empty spots are filled.',
        why: '70 is larger than 50, so it belongs on the right.',
        comparisonFormula: '70 > 50 → Go Right',
        banner: { text: '70 > 50 → Goes on the RIGHT', subtext: 'BST Right rule', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 50, state: 'default' },
          { id: '30', value: 30, x: 170, y: 130, state: 'default' },
          { id: '70', value: 70, x: 370, y: 130, state: 'active', badge: 'RIGHT: 70 > 50' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Repeat until an empty position is found',
        shortSentence: 'Repeat until an empty position is found.',
        currentStep: 'Repeat until an empty position is found.',
        whatNext: 'The BST is properly organized.',
        why: 'Every level follows the exact same rule.',
        banner: { text: 'BST Golden Rule: Left < Root < Right', subtext: 'Valid BST constructed', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 50, state: 'found', badge: 'ROOT' },
          { id: '30', value: 30, x: 170, y: 130, state: 'found', badge: '< 50' },
          { id: '70', value: 70, x: 370, y: 130, state: 'found', badge: '> 50' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 4: BST Property (The Golden Rule)
  4: {
    topicNumber: 4,
    topicTitle: 'BST Property (The Golden Rule)',
    shortTitle: 'BST Property',
    rule: 'Left < Root < Right',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Look at the root node value',
        shortSentence: 'Look at the root node value (50).',
        currentStep: 'Look at the root node value (50).',
        whatNext: 'Check the left subtree values.',
        why: 'The root value is the boundary for all nodes.',
        banner: { text: 'Root Node: 50', subtext: 'Center of comparison', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Every node in the left subtree must be smaller',
        shortSentence: 'Every node in the left subtree must be smaller than 50.',
        currentStep: 'Every node in the left subtree must be smaller than 50.',
        whatNext: 'Check the right subtree values.',
        why: 'Nodes 20, 30, and 40 are all strictly less than 50.',
        banner: { text: 'Left Subtree {20, 30, 40} < 50', subtext: 'All smaller than root', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: '< 50' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: '< 50' },
          { id: '40', value: 40, x: 230, y: 180, state: 'active', badge: '< 50' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Every node in the right subtree must be larger',
        shortSentence: 'Every node in the right subtree must be larger than 50.',
        currentStep: 'Every node in the right subtree must be larger than 50.',
        whatNext: 'Verify recursive property for subtrees.',
        why: 'Node 70 is strictly greater than 50.',
        banner: { text: 'Right Subtree {70} > 50', subtext: 'All larger than root', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: '> 50' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: This rule applies recursively to every subtree',
        shortSentence: 'This rule applies recursively to every subtree.',
        currentStep: 'This rule applies recursively to every subtree.',
        whatNext: 'Tree property confirmed.',
        why: 'For example, at node 30: 20 < 30 < 40.',
        banner: { text: '✓ Golden Rule Holds Everywhere', subtext: 'Left < Root < Right at every node', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: '20 < 30 < 40' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
    ],
  },

  // Topic 5: Finding the Root
  5: {
    topicNumber: 5,
    topicTitle: 'Finding the Root',
    shortTitle: 'Root Node',
    rule: 'Root = Topmost Node with 0 Parents',
    totalSteps: 3,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Look at the top node',
        shortSentence: 'Look at the top node in the tree.',
        currentStep: 'Look at the top node in the tree.',
        whatNext: 'Check if any parent points to it.',
        why: 'Every tree starts at the highest point.',
        banner: { text: 'Inspect Top Node (50)', subtext: 'Starting top of tree', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'TOP NODE' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: The top node has no parent',
        shortSentence: 'The top node has no parent above it.',
        currentStep: 'The top node has no parent above it.',
        whatNext: 'Confirm root status.',
        why: 'All other nodes have exactly one incoming parent edge.',
        banner: { text: 'Incoming Parent Edges = 0', subtext: 'No node sits above 50', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: 'PARENT = NULL' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: That node is the root',
        shortSentence: 'That node is the root.',
        currentStep: 'That node is the root.',
        whatNext: 'Root identified.',
        why: 'Node 50 is the official root of this BST.',
        banner: { text: '✓ Node 50 is the Root', subtext: 'Root node identified', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 6: Finding a Parent and Child Node
  6: {
    topicNumber: 6,
    topicTitle: 'Finding a Parent Node & Child Node',
    shortTitle: 'Parent & Child',
    rule: 'Parent sits above; Children sit below',
    totalSteps: 3,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Select a node',
        shortSentence: 'Select node 30 in the tree.',
        currentStep: 'Select node 30 in the tree.',
        whatNext: 'Look at the node directly above it.',
        why: 'We use node 30 as our focal point.',
        banner: { text: 'Selected Node: [ 30 ]', subtext: 'Finding parent and children', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'SELECTED' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Look at the node directly above it to find its parent',
        shortSentence: 'Look at the node directly above it: 50 is the parent.',
        currentStep: 'Look at the node directly above it: 50 is the parent.',
        whatNext: 'Look at the nodes directly below it.',
        why: 'Node 50 connects directly down to 30.',
        banner: { text: 'Parent of 30 is Node 50', subtext: 'Direct ancestor above', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: 'PARENT' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'CHILD OF 50' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Look at the nodes directly below it to find its children',
        shortSentence: 'Look at the nodes directly below it: 20 and 40 are its children.',
        currentStep: 'Look at the nodes directly below it: 20 and 40 are its children.',
        whatNext: 'Parent and children identified.',
        why: 'Node 20 is left child and 40 is right child of 30.',
        banner: { text: 'Children of 30 are 20 (Left) and 40 (Right)', subtext: 'Direct descendants below', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight', badge: 'PARENT OF {20,40}' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'LEFT CHILD' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: 'RIGHT CHILD' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
    ],
  },

  // Topic 7: Finding a Leaf Node
  7: {
    topicNumber: 7,
    topicTitle: 'Finding a Leaf Node',
    shortTitle: 'Leaf Node',
    rule: 'Leaf = Node with 0 Children',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Select a node',
        shortSentence: 'Select node 20 to test if it is a leaf.',
        currentStep: 'Select node 20 to test if it is a leaf.',
        whatNext: 'Check its left child.',
        why: 'Any candidate node can be tested.',
        banner: { text: 'Testing Node 20', subtext: 'Checking child pointers', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'TEST NODE' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Check its left child',
        shortSentence: 'Check its left child: it is empty (NULL).',
        currentStep: 'Check its left child: it is empty (NULL).',
        whatNext: 'Check its right child.',
        why: 'No branch extends to the left.',
        banner: { text: 'Left Child = NULL (Empty)', subtext: 'No left branch', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight', badge: 'LEFT: NULL', showNullLeft: true },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Check its right child',
        shortSentence: 'Check its right child: it is also empty (NULL).',
        currentStep: 'Check its right child: it is also empty (NULL).',
        whatNext: 'Evaluate leaf condition.',
        why: 'No branch extends to the right.',
        banner: { text: 'Right Child = NULL (Empty)', subtext: 'No right branch', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight', badge: 'RIGHT: NULL', showNullLeft: true, showNullRight: true },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: If both are empty, it is a leaf',
        shortSentence: 'If both are empty, it is a leaf.',
        currentStep: 'If both are empty, it is a leaf.',
        whatNext: 'Conclude leaf property.',
        why: 'Both left and right child pointers are null.',
        banner: { text: 'Left = NULL & Right = NULL → It is a LEAF', subtext: 'Leaf rule satisfied', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'LEAF NODE' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: A leaf has no children',
        shortSentence: 'A leaf has no children.',
        currentStep: 'A leaf has no children.',
        whatNext: 'All leaves identified.',
        why: 'Nodes 20, 40, and 70 are all leaves in this tree.',
        banner: { text: 'Leaves: {20, 40, 70}', subtext: 'All bottom terminal nodes', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'LEAF' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'LEAF' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: 'LEAF' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
    ],
  },

  // Topic 8: Subtree (Left & Right)
  8: {
    topicNumber: 8,
    topicTitle: 'Subtree (Left & Right)',
    shortTitle: 'Subtree',
    rule: 'Every subtree is itself a complete valid BST',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Select any node in the BST',
        shortSentence: 'Select root node 50 as our reference point.',
        currentStep: 'Select root node 50 as our reference point.',
        whatNext: 'Look at the left subtree.',
        why: 'Subtrees branch out below any selected node.',
        banner: { text: 'Reference Node: 50', subtext: 'Splitting into subtrees', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Everything down the left branch forms the left subtree',
        shortSentence: 'Everything down the left branch forms the left subtree ({20, 30, 40}).',
        currentStep: 'Everything down the left branch forms the left subtree ({20, 30, 40}).',
        whatNext: 'Look at the right subtree.',
        why: 'All nodes on the left branch are rooted at 30.',
        banner: { text: 'Left Subtree = {20, 30, 40}', subtext: 'All strictly < 50', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'LEFT SUBTREE' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'LEFT SUBTREE' },
          { id: '40', value: 40, x: 230, y: 180, state: 'active', badge: 'LEFT SUBTREE' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Everything down the right branch forms the right subtree',
        shortSentence: 'Everything down the right branch forms the right subtree ({70, 80}).',
        currentStep: 'Everything down the right branch forms the right subtree ({70, 80}).',
        whatNext: 'Verify subtree validity.',
        why: 'All nodes on the right branch are rooted at 70.',
        banner: { text: 'Right Subtree = {70, 80}', subtext: 'All strictly > 50', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'RIGHT SUBTREE' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'active', badge: 'RIGHT SUBTREE' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Each subtree is itself a complete valid BST',
        shortSentence: 'Each subtree is itself a complete valid BST.',
        currentStep: 'Each subtree is itself a complete valid BST.',
        whatNext: 'Subtree properties established.',
        why: 'Recursion works because every subtree obeys the BST rule.',
        banner: { text: '✓ Subtrees are Independent BSTs', subtext: 'Recursive property holds', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'ROOT' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'L-ROOT' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'R-ROOT' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 9: Height of a BST
  9: {
    topicNumber: 9,
    topicTitle: 'Height of a BST',
    shortTitle: 'Tree Height',
    rule: 'Height = Max(Left Height, Right Height) + 1',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the leaf nodes (height 0)',
        shortSentence: 'Start at the leaf nodes (height 0).',
        currentStep: 'Start at the leaf nodes (height 0).',
        whatNext: 'Move up to the parent nodes.',
        why: 'A single leaf node with no children has a height of 0.',
        banner: { text: 'Leaves: Height = 0', subtext: 'Base cases at bottom', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'H = 0' },
          { id: '40', value: 40, x: 230, y: 180, state: 'active', badge: 'H = 0' },
          { id: '80', value: 80, x: 410, y: 180, state: 'active', badge: 'H = 0' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Move up to each parent node',
        shortSentence: 'Move up to each parent node (30 and 70).',
        currentStep: 'Move up to each parent node (30 and 70).',
        whatNext: 'Calculate their heights.',
        why: 'Heights are calculated from bottom up to root.',
        banner: { text: 'Advance Upward to Level 1', subtext: 'Parents 30 and 70', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight', badge: 'CALC H' },
          { id: '70', value: 70, x: 360, y: 110, state: 'highlight', badge: 'CALC H' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default', badge: 'H = 0' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default', badge: 'H = 0' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default', badge: 'H = 0' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'active' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Take the larger height between left and right children, plus 1',
        shortSentence: 'Take the larger height between left and right children, plus 1.',
        currentStep: 'Take the larger height between left and right children, plus 1.',
        whatNext: 'Continue upward to the root.',
        why: 'Height of 30 = Max(0, 0) + 1 = 1.',
        comparisonFormula: 'Height = Max(H_left, H_right) + 1 = 1',
        banner: { text: 'Height(30) = 1  |  Height(70) = 1', subtext: 'Max(0,0) + 1 = 1', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'H = 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'H = 1' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default', badge: 'H = 0' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default', badge: 'H = 0' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default', badge: 'H = 0' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Continue upward to the root',
        shortSentence: 'Continue upward to the root node (50).',
        currentStep: 'Continue upward to the root node (50).',
        whatNext: 'Calculate total tree height.',
        why: 'Root height is Max(Height(30), Height(70)) + 1 = Max(1, 1) + 1 = 2.',
        comparisonFormula: 'Height(50) = Max(1, 1) + 1 = 2',
        banner: { text: 'Root Height: Max(1, 1) + 1 = 2', subtext: '2 edges from root to deepest leaf', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: 'H = 2' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default', badge: 'H = 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default', badge: 'H = 1' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default', badge: 'H = 0' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default', badge: 'H = 0' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default', badge: 'H = 0' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 4,
        title: "Step 5: The root's height is the height of the BST",
        shortSentence: "The root's height (2) is the height of the BST.",
        currentStep: "The root's height (2) is the height of the BST.",
        whatNext: 'Tree height computed.',
        why: 'Longest path from root to any leaf has 2 edges.',
        banner: { text: '✓ Total BST Height = 2', subtext: 'Max edges from root to leaf', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'BST HEIGHT = 2' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'H = 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'H = 1' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'H = 0' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: 'H = 0' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found', badge: 'H = 0' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 10: Depth of a Node
  10: {
    topicNumber: 10,
    topicTitle: 'Depth of a Node',
    shortTitle: 'Node Depth',
    rule: 'Depth = Number of Edges from Root down to Node',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root (depth 0)',
        shortSentence: 'Start at the root node (50), which has depth 0.',
        currentStep: 'Start at the root node (50), which has depth 0.',
        whatNext: 'Count edges down to target node 20.',
        why: 'Root is the top origin with 0 edges traversed.',
        banner: { text: 'Root (50): Depth = 0', subtext: 'Target is Node 20', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'DEPTH 0' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'target', badge: 'TARGET: 20' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Follow the edge down to node 30',
        shortSentence: 'Follow the edge down to node 30 (depth increases to 1).',
        currentStep: 'Follow the edge down to node 30 (depth increases to 1).',
        whatNext: 'Follow the next edge to node 20.',
        why: 'Traversing 1 edge adds +1 to depth.',
        banner: { text: '1 Edge Down → Node 30: Depth = 1', subtext: '1 step from root', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'DEPTH 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'target', badge: 'TARGET: 20' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Follow the edge down to node 20',
        shortSentence: 'Follow the edge down to node 20 (depth increases to 2).',
        currentStep: 'Follow the edge down to node 20 (depth increases to 2).',
        whatNext: 'Record the final depth.',
        why: 'Traversing 2 edges from root brings us to node 20.',
        banner: { text: '2 Edges Down → Node 20: Depth = 2', subtext: 'Target reached', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default', badge: 'DEPTH 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight', badge: 'DEPTH 2' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: The total step count is the depth of the node',
        shortSentence: 'The total edge count (2) is the depth of node 20.',
        currentStep: 'The total edge count (2) is the depth of node 20.',
        whatNext: 'Depth calculation complete.',
        why: 'Depth measures downward distance from root.',
        banner: { text: '✓ Depth of Node 20 is 2', subtext: '2 edges from root', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'DEPTH 0' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found', badge: 'DEPTH 1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found', badge: 'DEPTH 1' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'DEPTH 2' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
        ],
      },
    ],
  },

  // Topic 11: Balanced vs Skewed BST
  11: {
    topicNumber: 11,
    topicTitle: 'Balanced vs Skewed BST',
    shortTitle: 'Balanced vs Skewed',
    rule: '|Left Height - Right Height| ≤ 1 for Balanced',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Calculate the height of the left and right subtrees',
        shortSentence: 'Calculate the height of the left and right subtrees.',
        currentStep: 'Calculate the height of the left and right subtrees.',
        whatNext: 'Compare the two heights.',
        why: 'Subtree heights determine the balance factor.',
        banner: { text: 'Inspect Subtree Heights', subtext: 'Left H = 1, Right H = 1', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight', badge: 'LEFT: H=1' },
          { id: '70', value: 70, x: 360, y: 110, state: 'highlight', badge: 'RIGHT: H=1' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'active' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Compare the two heights',
        shortSentence: 'Compare the two heights: |1 - 1| = 0.',
        currentStep: 'Compare the two heights: |1 - 1| = 0.',
        whatNext: 'Check balance condition.',
        why: 'Difference of heights is called the Balance Factor.',
        comparisonFormula: '|H_left - H_right| = |1 - 1| = 0 ≤ 1',
        banner: { text: 'Height Difference = 0', subtext: 'Balanced condition satisfied', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'BALANCED' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: If the difference is at most 1, the tree is balanced',
        shortSentence: 'If the difference is at most 1, the tree is balanced (O(log N) operations).',
        currentStep: 'If the difference is at most 1, the tree is balanced (O(log N) operations).',
        whatNext: 'Examine a skewed tree.',
        why: 'Balanced trees guarantee fast logarithmic search times.',
        banner: { text: 'Balanced BST = Fast O(log N)', subtext: 'Even distribution of nodes', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'O(log N)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: If all nodes lean to one side, it is skewed',
        shortSentence: 'If all nodes lean to one side, it is skewed and degrades to O(N).',
        currentStep: 'If all nodes lean to one side, it is skewed and degrades to O(N).',
        whatNext: 'Ready for BST operations.',
        why: 'Skewed trees behave like linear linked lists.',
        banner: { text: 'Skewed Tree = Slow O(N) List', subtext: 'Avoid by auto-balancing', type: 'WARNING' },
        nodes: [
          { id: '10', value: 10, x: 200, y: 40, state: 'warning', badge: 'ROOT' },
          { id: '20', value: 20, x: 250, y: 110, state: 'warning', badge: 'RIGHT ONLY' },
          { id: '30', value: 30, x: 300, y: 180, state: 'warning', badge: 'SKEWED' },
        ],
        edges: [
          { fromId: '10', toId: '20', state: 'active' },
          { fromId: '20', toId: '30', state: 'active' },
        ],
      },
    ],
  },
};
