import { TopicAnimationData } from './types';

export const TOPICS_OPERATIONS: Record<number, TopicAnimationData> = {
  // Topic 12: Searching for a Node (Search 60)
  12: {
    topicNumber: 12,
    topicTitle: 'Searching for a Node',
    shortTitle: 'BST Search',
    rule: 'Target < Current → Left | Target > Current → Right',
    totalSteps: 6,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Compare 60 with 50.',
        why: 'Every search in a BST begins at the root.',
        banner: { text: 'Search Target: [ 60 ]', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 120, y: 180, state: 'default' },
          { id: '40', value: 40, x: 240, y: 180, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'target', badge: 'TARGET' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
        prediction: {
          question: 'We are at root 50 and searching for 60. Since 60 > 50, where do we go?',
          options: ['Move RIGHT to node 70', 'Move LEFT to node 30', 'Stop, 60 is not in tree'],
          correctIndex: 0,
          hint: 'Remember the BST rule: larger values live in the right subtree.',
          explanation: 'Since 60 > 50, the target must be in the right subtree.',
        },
      },
      {
        stepIndex: 1,
        title: 'Step 2: Compare 60 with the current node',
        shortSentence: 'Compare 60 with the current node (50).',
        currentStep: 'Compare 60 with the current node (50).',
        whatNext: '60 is larger than 50.',
        why: 'Comparison tells us which subtree to eliminate.',
        comparisonFormula: '60 > 50 → Discard Left Subtree',
        banner: { text: '60 > 50 → Discard Left Subtree', subtext: 'Halving search space', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: '60 > 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed', label: 'Discarded' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 120, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 240, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'target' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: If 60 is larger, move right',
        shortSentence: 'If 60 is larger, move right to node 70.',
        currentStep: 'If 60 is larger, move right to node 70.',
        whatNext: 'Compare 60 with 70.',
        why: '60 > 50 so we traverse to the right child.',
        banner: { text: 'Move RIGHT to Node 70', subtext: 'Active search pointer moves', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'CURRENT: 70' },
          { id: '20', value: 20, x: 120, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 240, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'target' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Repeat the comparison',
        shortSentence: 'Repeat the comparison: 60 is smaller than 70.',
        currentStep: 'Repeat the comparison: 60 is smaller than 70.',
        whatNext: 'Move left from 70.',
        why: '60 < 70 means the target lies in the left branch of 70.',
        comparisonFormula: '60 < 70 → Move Left',
        banner: { text: '60 < 70 → Move LEFT', subtext: 'Discarding node 80', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'highlight', badge: '60 < 70' },
          { id: '20', value: 20, x: 120, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 240, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'target' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed', label: 'Discarded' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Move to node 60',
        shortSentence: 'Move left to node 60.',
        currentStep: 'Move left to node 60.',
        whatNext: 'Compare values for a match.',
        why: 'The active pointer arrives at node 60.',
        banner: { text: 'Arrived at Node 60', subtext: 'Checking equality', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 120, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 240, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'active', badge: 'COMPARE: 60 == 60' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 5,
        title: 'Step 6: If the value matches, the node is found',
        shortSentence: 'If the value matches (60 == 60), the node is found.',
        currentStep: 'If the value matches (60 == 60), the node is found.',
        whatNext: 'Search completes successfully.',
        why: 'Target key matches the current node value exactly.',
        comparisonFormula: '60 == 60 → FOUND ✓',
        banner: { text: '✓ Node 60 Found Successfully!', subtext: 'Completed in O(log N) comparisons', type: 'FOUND' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 120, y: 180, state: 'default' },
          { id: '40', value: 40, x: 240, y: 180, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'found', badge: 'FOUND (60)' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 13: Inserting a Node (Example: Insert 30)
  13: {
    topicNumber: 13,
    topicTitle: 'Inserting a Node',
    shortTitle: 'BST Insert',
    rule: 'Traverse until empty position (NULL), then insert',
    totalSteps: 6,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root',
        shortSentence: 'Start at the root node (50) with new value 30.',
        currentStep: 'Start at the root node (50) with new value 30.',
        whatNext: 'Compare 30 with 50.',
        why: 'All insertions begin from the root reference.',
        banner: { text: 'Insert Value: [ 30 ]', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '70', value: 70, x: 370, y: 110, state: 'default' },
        ],
        edges: [{ fromId: '50', toId: '70', state: 'default' }],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Compare 30 with the current node',
        shortSentence: 'Compare 30 with the current node (50).',
        currentStep: 'Compare 30 with the current node (50).',
        whatNext: 'Decide left or right direction.',
        why: '30 is less than 50.',
        comparisonFormula: '30 < 50 → Move Left',
        banner: { text: '30 < 50 → Move LEFT', subtext: 'Must belong in left subtree', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: '30 < 50' },
          { id: '70', value: 70, x: 370, y: 110, state: 'dimmed' },
        ],
        edges: [{ fromId: '50', toId: '70', state: 'dimmed' }],
      },
      {
        stepIndex: 2,
        title: 'Step 3: If 30 is smaller, move left',
        shortSentence: 'If 30 is smaller, move left.',
        currentStep: 'If 30 is smaller, move left.',
        whatNext: 'Check if left child exists.',
        why: 'Left pointer of 50 is currently empty (NULL).',
        banner: { text: 'Move LEFT: Position is Empty (NULL)', subtext: 'Found insertion slot', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'LEFT = NULL', showNullLeft: true },
          { id: '70', value: 70, x: 370, y: 110, state: 'dimmed' },
        ],
        edges: [{ fromId: '50', toId: '70', state: 'dimmed' }],
      },
      {
        stepIndex: 3,
        title: 'Step 4: If 30 is larger, move right',
        shortSentence: 'If 30 is larger, move right (not applicable here since 30 < 50).',
        currentStep: 'If 30 is larger, move right (not applicable here since 30 < 50).',
        whatNext: 'Continue to empty spot.',
        why: 'We skip moving right because 30 < 50.',
        banner: { text: 'Right branch not taken', subtext: '30 belongs strictly on Left', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active' },
          { id: '70', value: 70, x: 370, y: 110, state: 'dimmed' },
        ],
        edges: [{ fromId: '50', toId: '70', state: 'dimmed' }],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Continue until an empty position is found',
        shortSentence: 'Continue until an empty position is found.',
        currentStep: 'Continue until an empty position is found.',
        whatNext: 'Place 30 in that position.',
        why: 'Empty slot confirmed at left child of 50.',
        banner: { text: 'Empty Slot Confirmed at Left of 50', subtext: 'Ready to attach new node', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: 'SLOT READY' },
          { id: '70', value: 70, x: 370, y: 110, state: 'default' },
        ],
        edges: [{ fromId: '50', toId: '70', state: 'default' }],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Place 30 in that position',
        shortSentence: 'Place 30 in that position as the left child of 50.',
        currentStep: 'Place 30 in that position as the left child of 50.',
        whatNext: 'Insertion complete.',
        why: 'New node 30 is attached and BST property is preserved.',
        banner: { text: '✓ Node 30 Successfully Inserted!', subtext: 'BST invariant maintained', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 170, y: 110, state: 'inserted', badge: 'NEW NODE' },
          { id: '70', value: 70, x: 370, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 14: Delete a Leaf Node
  14: {
    topicNumber: 14,
    topicTitle: 'Delete a Leaf Node (Case 1)',
    shortTitle: 'Delete Leaf',
    rule: '0 Children → Simply delete node and set parent pointer to NULL',
    totalSteps: 6,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Identify the node',
        shortSentence: 'Identify node 20 to delete from the tree.',
        currentStep: 'Identify node 20 to delete from the tree.',
        whatNext: 'Check its children.',
        why: 'Node 20 is targeted for deletion.',
        banner: { text: 'Target Deletion: [ 20 ]', subtext: 'Searching tree for node 20', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'target', badge: 'TARGET: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Check its children',
        shortSentence: 'Check its left and right children.',
        currentStep: 'Check its left and right children.',
        whatNext: 'Count how many children it has.',
        why: 'Number of children dictates which deletion case to use.',
        banner: { text: 'Checking Children of Node 20', subtext: 'Left = NULL, Right = NULL', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: '0 CHILDREN', showNullLeft: true, showNullRight: true },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: It has no children',
        shortSentence: 'It has no children (child count is 0).',
        currentStep: 'It has no children (child count is 0).',
        whatNext: 'Classify as leaf.',
        why: '0 children means Case 1 deletion.',
        banner: { text: 'Child Count = 0', subtext: 'Case 1 applies', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'highlight', badge: '0 CHILDREN' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: It is a leaf node',
        shortSentence: 'It is a leaf node.',
        currentStep: 'It is a leaf node.',
        whatNext: 'Remove the node directly.',
        why: 'Leaf deletion has no child subtree re-wiring needed.',
        banner: { text: 'Confirmed: Node 20 is a Leaf', subtext: 'Safe to remove directly', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight', badge: 'PARENT (30)' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'deleted', badge: 'LEAF' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'severed' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Remove the node',
        shortSentence: 'Remove the node.',
        currentStep: 'Remove the node.',
        whatNext: 'Remove the connection to the parent.',
        why: 'Node 20 is deleted from memory.',
        banner: { text: 'Node 20 Removed', subtext: 'Severing parent link', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'SET LEFT=NULL' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Remove the connection to the parent',
        shortSentence: 'Remove the connection to the parent (set parent.left = NULL).',
        currentStep: 'Remove the connection to the parent (set parent.left = NULL).',
        whatNext: 'Tree is clean and valid.',
        why: 'Parent node 30 now has left child = null.',
        banner: { text: '✓ Leaf Node 20 Deleted Cleanly', subtext: 'Parent left pointer set to null', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
    ],
  },

  // Topic 15: Delete a Node with One Child
  15: {
    topicNumber: 15,
    topicTitle: 'Delete a Node with One Child (Case 2)',
    shortTitle: 'Delete 1 Child',
    rule: '1 Child → Bypass deleted node and connect parent directly to child',
    totalSteps: 6,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Identify the node',
        shortSentence: 'Identify node 30 to delete.',
        currentStep: 'Identify node 30 to delete.',
        whatNext: 'Check its children.',
        why: 'Node 30 is targeted for deletion.',
        banner: { text: 'Target Deletion: [ 30 ]', subtext: 'Checking child count', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default', badge: 'PARENT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'target', badge: 'TARGET: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '40', value: 40, x: 220, y: 180, state: 'default', badge: 'CHILD: 40' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Check its children',
        shortSentence: 'Check its children: left is empty, right is 40.',
        currentStep: 'Check its children: left is empty, right is 40.',
        whatNext: 'Verify child count is 1.',
        why: 'Left is null and right is node 40.',
        banner: { text: 'Left = NULL, Right = Node 40', subtext: 'Exact count is 1 child', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: '1 CHILD' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '40', value: 40, x: 220, y: 180, state: 'highlight', badge: 'ONLY CHILD' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: It has one child',
        shortSentence: 'It has one child (Case 2 deletion).',
        currentStep: 'It has one child (Case 2 deletion).',
        whatNext: 'Connect parent directly to child.',
        why: 'When a node has 1 child, the child bypasses the deleted node.',
        banner: { text: 'Case 2: Node has 1 Child', subtext: 'Bypass rewiring needed', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'highlight', badge: 'PARENT' },
          { id: '30', value: 30, x: 180, y: 110, state: 'deleted', badge: 'BYPASS' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '40', value: 40, x: 220, y: 180, state: 'active', badge: 'PROMOTED' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'severed' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '40', state: 'severed' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Connect the parent directly to the child',
        shortSentence: 'Connect parent (50) directly to child (40).',
        currentStep: 'Connect parent (50) directly to child (40).',
        whatNext: 'Delete original node 30.',
        why: '50.left is updated to point directly to 40.',
        banner: { text: 'Rewiring: 50.left → 40', subtext: 'Parent connects to grandchild', type: 'REWIRE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'REWIRED' },
          { id: '30', value: 30, x: 140, y: 110, state: 'deleted', badge: 'REMOVED' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '40', value: 40, x: 180, y: 110, state: 'child-replace', badge: 'TAKES POSITION' },
        ],
        edges: [
          { fromId: '50', toId: '40', state: 'rewired' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: Delete the original node',
        shortSentence: 'Delete the original node (30).',
        currentStep: 'Delete the original node (30).',
        whatNext: 'Child finishes taking position.',
        why: 'Node 30 is removed from the BST structure.',
        banner: { text: 'Node 30 Deleted', subtext: 'Removed from tree', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '40', value: 40, x: 180, y: 110, state: 'active', badge: 'NEW LEFT CHILD' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '40', state: 'active' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
      {
        stepIndex: 5,
        title: 'Step 6: The child takes its position',
        shortSentence: 'The child (40) takes its position in the tree.',
        currentStep: 'The child (40) takes its position in the tree.',
        whatNext: 'Case 2 deletion complete.',
        why: 'Tree is balanced and BST property is fully preserved (40 < 50).',
        banner: { text: '✓ Child 40 Takes Position', subtext: 'Valid BST preserved (40 < 50)', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found' },
          { id: '40', value: 40, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '40', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
        ],
      },
    ],
  },

  // Topic 16: Delete a Node with Two Children
  16: {
    topicNumber: 16,
    topicTitle: 'Delete a Node with Two Children (Case 3)',
    shortTitle: 'Delete 2 Children',
    rule: '2 Children → Replace with In-order Successor and delete original successor',
    totalSteps: 7,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Identify the node',
        shortSentence: 'Identify node 50 to delete from the tree.',
        currentStep: 'Identify node 50 to delete from the tree.',
        whatNext: 'Check its children.',
        why: 'Node 50 is targeted for deletion.',
        banner: { text: 'Target Deletion: [ 50 ]', subtext: 'Root node targeted', type: 'DELETE' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'target', badge: 'TARGET: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'default' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Check its children',
        shortSentence: 'Check its children: left is 30, right is 70.',
        currentStep: 'Check its children: left is 30, right is 70.',
        whatNext: 'Verify child count.',
        why: 'Both left and right branches exist.',
        banner: { text: 'Left = 30, Right = 70', subtext: 'Both children present', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: '2 CHILDREN' },
          { id: '30', value: 30, x: 180, y: 110, state: 'highlight' },
          { id: '70', value: 70, x: 360, y: 110, state: 'highlight' },
          { id: '60', value: 60, x: 320, y: 180, state: 'default' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: It has two children',
        shortSentence: 'It has two children (Case 3 deletion).',
        currentStep: 'It has two children (Case 3 deletion).',
        whatNext: 'Find its in-order successor.',
        why: 'We cannot simply delete it; we must find a safe replacement.',
        banner: { text: 'Case 3: Node has 2 Children', subtext: 'Find in-order successor to replace', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'target', badge: 'REPLACE ME' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'default' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Find its in-order successor',
        shortSentence: 'Find its in-order successor (smallest node in right subtree = 60).',
        currentStep: 'Find its in-order successor (smallest node in right subtree = 60).',
        whatNext: "Copy the successor's value.",
        why: '60 is the next smallest node larger than 50.',
        banner: { text: 'In-order Successor = Node 60', subtext: 'Smallest node in right subtree', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'target', badge: 'REPLACE' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'successor', badge: 'SUCCESSOR (60)' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'successor' },
          { fromId: '70', toId: '60', state: 'successor' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 4,
        title: "Step 5: Copy the successor's value",
        shortSentence: "Copy the successor's value (60) into the root position.",
        currentStep: "Copy the successor's value (60) into the root position.",
        whatNext: 'Delete original successor node.',
        why: 'Node 50 now holds value 60.',
        banner: { text: 'Value 60 Copied to Root', subtext: 'Original successor 60 still at bottom', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 60, x: 270, y: 40, state: 'active', badge: 'COPIED 60' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'deleted', badge: 'DELETE DUPLICATE' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '70', toId: '60', state: 'severed' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 5,
        title: 'Step 6: Delete the original successor node',
        shortSentence: 'Delete the original successor node (60) from the right subtree.',
        currentStep: 'Delete the original successor node (60) from the right subtree.',
        whatNext: 'The BST is updated.',
        why: 'Deleting a leaf or 1-child successor is simple.',
        banner: { text: 'Duplicate Successor Deleted', subtext: 'Right subtree cleaned', type: 'DELETE' },
        nodes: [
          { id: '50', value: 60, x: 270, y: 40, state: 'active', badge: 'ROOT: 60' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 6,
        title: 'Step 7: The BST is updated',
        shortSentence: 'The BST is updated and all BST rules hold.',
        currentStep: 'The BST is updated and all BST rules hold.',
        whatNext: 'Case 3 deletion complete.',
        why: 'Left subtree {30} < 60 < Right subtree {70, 80}.',
        banner: { text: '✓ Case 3 Deletion Complete', subtext: 'BST properties 100% intact', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 60, x: 270, y: 40, state: 'found', badge: 'ROOT: 60' },
          { id: '30', value: 30, x: 180, y: 110, state: 'found' },
          { id: '70', value: 70, x: 360, y: 110, state: 'found' },
          { id: '80', value: 80, x: 400, y: 180, state: 'found' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 17: Finding the In-order Predecessor
  17: {
    topicNumber: 17,
    topicTitle: 'Finding the In-order Predecessor',
    shortTitle: 'Predecessor',
    rule: 'Predecessor = Largest node in Left subtree (Left → Far Right)',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Select the node',
        shortSentence: 'Select node 50 as our reference node.',
        currentStep: 'Select node 50 as our reference node.',
        whatNext: 'Move to its left child.',
        why: 'Predecessor is the largest value smaller than 50.',
        banner: { text: 'Find Predecessor of Node [ 50 ]', subtext: 'Largest node smaller than 50', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'REFERENCE: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Move to its left child',
        shortSentence: 'Move to its left child (node 30).',
        currentStep: 'Move to its left child (node 30).',
        whatNext: 'Move right as far as possible.',
        why: 'All smaller nodes reside in the left subtree.',
        banner: { text: 'Step 1: Move LEFT to Node 30', subtext: 'Entering left subtree', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'LEFT CHILD' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Move right as far as possible',
        shortSentence: 'Move right as far as possible.',
        currentStep: 'Move right as far as possible.',
        whatNext: 'Check if any more right branches exist.',
        why: 'In any subtree, larger elements are found by going right.',
        banner: { text: 'Step 2: Move RIGHT to Node 40', subtext: 'Following right pointers', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'highlight', badge: 'RIGHTMOST' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Stop at the largest node',
        shortSentence: 'Stop at the largest node (40 has no right child).',
        currentStep: 'Stop at the largest node (40 has no right child).',
        whatNext: 'Identify as predecessor.',
        why: 'Right pointer is null, so 40 is maximum in this subtree.',
        banner: { text: 'Node 40 has no right child', subtext: 'Maximum node reached', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '40', value: 40, x: 230, y: 180, state: 'active', badge: 'STOP HERE', showNullRight: true },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: That node is the in-order predecessor',
        shortSentence: 'That node (40) is the in-order predecessor of 50.',
        currentStep: 'That node (40) is the in-order predecessor of 50.',
        whatNext: 'Predecessor found.',
        why: 'In-order sequence places 40 immediately before 50.',
        banner: { text: '✓ In-order Predecessor of 50 is 40', subtext: 'Immediate predecessor in sorted order', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'NODE (50)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default' },
          { id: '40', value: 40, x: 230, y: 180, state: 'found', badge: 'PREDECESSOR (40)' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'active' },
        ],
      },
    ],
  },

  // Topic 18: Finding the In-order Successor
  18: {
    topicNumber: 18,
    topicTitle: 'Finding the In-order Successor',
    shortTitle: 'Successor',
    rule: 'Successor = Smallest node in Right subtree (Right → Far Left)',
    totalSteps: 5,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Select the node',
        shortSentence: 'Select node 50 as our reference node.',
        currentStep: 'Select node 50 as our reference node.',
        whatNext: 'Move to its right child.',
        why: 'Successor is the smallest value larger than 50.',
        banner: { text: 'Find Successor of Node [ 50 ]', subtext: 'Smallest node larger than 50', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'REFERENCE: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Move to its right child',
        shortSentence: 'Move to its right child (node 70).',
        currentStep: 'Move to its right child (node 70).',
        whatNext: 'Move left as far as possible.',
        why: 'All larger nodes reside in the right subtree.',
        banner: { text: 'Step 1: Move RIGHT to Node 70', subtext: 'Entering right subtree', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'RIGHT CHILD' },
          { id: '60', value: 60, x: 320, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '70', toId: '60', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Move left as far as possible',
        shortSentence: 'Move left as far as possible.',
        currentStep: 'Move left as far as possible.',
        whatNext: 'Check if any more left branches exist.',
        why: 'In any subtree, smaller elements are found by going left.',
        banner: { text: 'Step 2: Move LEFT to Node 60', subtext: 'Following left pointers', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'highlight', badge: 'LEFTMOST' },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Stop at the smallest node',
        shortSentence: 'Stop at the smallest node (60 has no left child).',
        currentStep: 'Stop at the smallest node (60 has no left child).',
        whatNext: 'Identify as successor.',
        why: 'Left pointer is null, so 60 is minimum in this right subtree.',
        banner: { text: 'Node 60 has no left child', subtext: 'Minimum node reached', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'active', badge: 'STOP HERE', showNullLeft: true },
          { id: '80', value: 80, x: 400, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 4,
        title: 'Step 5: That node is the in-order successor',
        shortSentence: 'That node (60) is the in-order successor of 50.',
        currentStep: 'That node (60) is the in-order successor of 50.',
        whatNext: 'Successor found.',
        why: 'In-order sequence places 60 immediately after 50.',
        banner: { text: '✓ In-order Successor of 50 is 60', subtext: 'Immediate successor in sorted order', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'found', badge: 'NODE (50)' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '60', value: 60, x: 320, y: 180, state: 'found', badge: 'SUCCESSOR (60)' },
          { id: '80', value: 80, x: 400, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '70', toId: '60', state: 'active' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
    ],
  },

  // Topic 19: Find Minimum & Maximum
  19: {
    topicNumber: 19,
    topicTitle: 'Find Minimum & Maximum',
    shortTitle: 'Min & Max',
    rule: 'Min = Leftmost node | Max = Rightmost node',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root node',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Follow left branches for minimum.',
        why: 'The root is the starting point for both extremes.',
        banner: { text: 'Starting at Root (50)', subtext: 'Exploring extremes', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Follow the left branches all the way to find the minimum',
        shortSentence: 'Follow the left branches all the way down to find the minimum (20).',
        currentStep: 'Follow the left branches all the way down to find the minimum (20).',
        whatNext: 'Follow right branches for maximum.',
        why: 'Because all left nodes are smaller, leftmost leaf must be minimum.',
        banner: { text: 'Leftmost Path: 50 → 30 → 20 (MIN)', subtext: 'Minimum element found', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'MIN: 20' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Follow the right branches all the way to find the maximum',
        shortSentence: 'Follow the right branches all the way down to find the maximum (80).',
        currentStep: 'Follow the right branches all the way down to find the maximum (80).',
        whatNext: 'Compare minimum and maximum.',
        why: 'Because all right nodes are larger, rightmost leaf must be maximum.',
        banner: { text: 'Rightmost Path: 50 → 70 → 80 (MAX)', subtext: 'Maximum element found', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'MIN: 20' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found', badge: 'MAX: 80' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: The leftmost node is minimum, and rightmost node is maximum',
        shortSentence: 'The leftmost node (20) is minimum, and rightmost node (80) is maximum.',
        currentStep: 'The leftmost node (20) is minimum, and rightmost node (80) is maximum.',
        whatNext: 'Min and max identified in O(h) time.',
        why: 'No full traversal needed; just traverse single leftmost/rightmost spine.',
        banner: { text: '✓ Min = 20  |  Max = 80', subtext: 'Both found in O(height) time', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default', badge: 'ROOT' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'MIN: 20' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found', badge: 'MAX: 80' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
    ],
  },

  // Dedicated Topic 101: Find Minimum
  101: {
    topicNumber: 101,
    topicTitle: 'Find Minimum Value',
    shortTitle: 'Minimum',
    rule: 'Move LEFT repeatedly until no left child exists',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root node',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Inspect the left child pointer.',
        why: 'All smaller elements in a BST reside in the left subtree.',
        banner: { text: 'Goal: Find Minimum Value', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'default' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Move to the left child',
        shortSentence: 'Move left to node 30.',
        currentStep: 'Move left to node 30.',
        whatNext: 'Check if node 30 has a left child.',
        why: '30 < 50, so any smaller value must be in the left subtree of 50.',
        banner: { text: 'Move LEFT to Node 30', subtext: '30 < 50', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'active', badge: 'CURRENT: 30' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'default' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'default' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Keep moving left as far as possible',
        shortSentence: 'Move left again to node 20.',
        currentStep: 'Move left again to node 20.',
        whatNext: 'Check if 20 has any left child.',
        why: '20 < 30, following the leftmost chain.',
        banner: { text: 'Move LEFT to Node 20', subtext: '20 < 30', type: 'LEFT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'active', badge: 'CURRENT: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Stop when there is no left child — Minimum Found',
        shortSentence: 'Node 20 has no left child. Node 20 is the Minimum value!',
        currentStep: 'Node 20 has no left child. Node 20 is the Minimum value!',
        whatNext: 'Minimum found in O(height) time.',
        why: 'Because there is no node to the left of 20, no smaller value exists in the BST.',
        banner: { text: '✓ Minimum Value = 20', subtext: 'Leftmost node in BST', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'default' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'found', badge: 'MIN: 20' },
          { id: '40', value: 40, x: 230, y: 180, state: 'default' },
          { id: '80', value: 80, x: 410, y: 180, state: 'dimmed' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'active' },
          { fromId: '50', toId: '70', state: 'dimmed' },
          { fromId: '30', toId: '20', state: 'active' },
          { fromId: '30', toId: '40', state: 'default' },
          { fromId: '70', toId: '80', state: 'dimmed' },
        ],
      },
    ],
  },

  // Dedicated Topic 102: Find Maximum
  102: {
    topicNumber: 102,
    topicTitle: 'Find Maximum Value',
    shortTitle: 'Maximum',
    rule: 'Move RIGHT repeatedly until no right child exists',
    totalSteps: 4,
    steps: [
      {
        stepIndex: 0,
        title: 'Step 1: Start at the root node',
        shortSentence: 'Start at the root node (50).',
        currentStep: 'Start at the root node (50).',
        whatNext: 'Inspect the right child pointer.',
        why: 'All larger elements in a BST reside in the right subtree.',
        banner: { text: 'Goal: Find Maximum Value', subtext: 'Starting at Root (50)', type: 'INFO' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'active', badge: 'ROOT: 50' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'default' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'default' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 1,
        title: 'Step 2: Move to the right child',
        shortSentence: 'Move right to node 70.',
        currentStep: 'Move right to node 70.',
        whatNext: 'Check if node 70 has a right child.',
        why: '70 > 50, so any larger value must be in the right subtree of 50.',
        banner: { text: 'Move RIGHT to Node 70', subtext: '70 > 50', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'active', badge: 'CURRENT: 70' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'default' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'default' },
        ],
      },
      {
        stepIndex: 2,
        title: 'Step 3: Keep moving right as far as possible',
        shortSentence: 'Move right again to node 80.',
        currentStep: 'Move right again to node 80.',
        whatNext: 'Check if 80 has any right child.',
        why: '80 > 70, following the rightmost chain.',
        banner: { text: 'Move RIGHT to Node 80', subtext: '80 > 70', type: 'RIGHT' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'dimmed' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'dimmed' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'dimmed' },
          { id: '80', value: 80, x: 410, y: 180, state: 'active', badge: 'CURRENT: 80' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'dimmed' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
      {
        stepIndex: 3,
        title: 'Step 4: Stop when there is no right child — Maximum Found',
        shortSentence: 'Node 80 has no right child. Node 80 is the Maximum value!',
        currentStep: 'Node 80 has no right child. Node 80 is the Maximum value!',
        whatNext: 'Maximum found in O(height) time.',
        why: 'Because there is no node to the right of 80, no larger value exists in the BST.',
        banner: { text: '✓ Maximum Value = 80', subtext: 'Rightmost node in BST', type: 'SUCCESS' },
        nodes: [
          { id: '50', value: 50, x: 270, y: 40, state: 'default' },
          { id: '30', value: 30, x: 180, y: 110, state: 'dimmed' },
          { id: '70', value: 70, x: 360, y: 110, state: 'default' },
          { id: '20', value: 20, x: 130, y: 180, state: 'dimmed' },
          { id: '60', value: 60, x: 320, y: 180, state: 'default' },
          { id: '80', value: 80, x: 410, y: 180, state: 'found', badge: 'MAX: 80' },
        ],
        edges: [
          { fromId: '50', toId: '30', state: 'dimmed' },
          { fromId: '50', toId: '70', state: 'active' },
          { fromId: '30', toId: '20', state: 'dimmed' },
          { fromId: '70', toId: '60', state: 'default' },
          { fromId: '70', toId: '80', state: 'active' },
        ],
      },
    ],
  },
};
